### ISSUE TITLE
[Feature request] Show command response in same pane as Send command button

### ISSUE THREAD

**Issue by BenPYeh** [Azure/azure-iot-explorer#107]
After I click send command a notification shows up and if it's successful it shows the command response which has some data I'm interested in but the notification doesn't persist. It would be useful to have it nearby the command button.

**Comment by YingXue** [comment]
Hi @BenPYeh,
The response is persisted and you can view it through clicking on the "Notification" button from the mashead.
![image](https://user-images.githubusercontent.com/5489222/64719608-732f7000-d47d-11e9-82e8-42fdf5cee1ae.png)
It is a design choice not to show it near the command button at the time.
Please let us know if it solves the problem for you.

**Comment by YingXue** [comment]
Closing the issue. Please reopen if applies.
