### ISSUE TITLE
x509 Device Connection String

### ISSUE THREAD

**Issue by jebrando** [Azure/azure-iot-explorer#117]
I'm unaware of a way to find the version of the iot-explorer to include here.

For x509 devices, there is no way to copy the connection strings into the device samples.  A connection string for x509 devices look like the following:

```Shell
HostName=<iothub_name>.azure-devices.net;DeviceId=x509_device;x509=true
```

Do you plan to support device connection string for x509 devices?

**Comment by YingXue** [comment]
The latest release 0.10.5 has the feature in. Closing the issue.
