### ISSUE TITLE
[Feature request] Adding version number on the UI 

### ISSUE THREAD

**Issue by anthonyvercolano** [Azure/azure-iot-explorer#122]
When I see a difference in behavior between what is happening on my machine with Azure IoT Explorer and what is happening on my co-workers machine, it would be nice to have a version number of the app to determine if we are running different explorers.

**Comment by YingXue** [comment]
Hi @anthonyvercolano,
Our latest release made one step closer towards this request.
By opening Help => About azure-iot-explorer from the tool bar, it would open a browser tab directing the users to the matching release page on the github which contains the version number. 
We will close this issue at this time, and keep improving on the user experience!
