### ISSUE TITLE
[Feature request] Support for Linux

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/azure-iot-explorer#136]
I would love to get support for Linux. Being able to download the application from this repository would be sufficient. I don't propose any integration with the package managers, at least not as an initial step.

**Comment by YingXue** [comment]
Hi there,
If you'd like to try download the source and build a linux app yourself, here is how you can do it: https://github.com/Azure/azure-iot-explorer/wiki/FAQ (only one command needed).
We are waiting for some dependency to be ready before we can ship a Linux app, and at the meantime, this is how our Linux customers are using the app at this point. Please give it a try and thank you very much for the input.

**Comment by mattias-kindborg-axis-communications** [comment]
Thanks, building it for Linux was as easy as you said!

You can choose whether you wish this issue to be open until you release the Linux support officially, or close it since we currently have an workaround, its your call.

**Comment by kartben** [comment]
Hi - is there an update on making a ready-to-use Linux package directly available from the official releases?

**Comment by c-ryan-k** [comment]
Hey folks, we're currently in the process of moving our release signing tasks over to a new VSO task - assuming all is well with #216 we should be able to start providing signed Debian packages alongside our Mac and Windows releases.

**Comment by c-ryan-k** [comment]
Our Linux package has arrived in our latest release!

Give it a try and let us know if you have any issues.
