### ISSUE TITLE
[BUG] Proxy support

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/azure-iot-explorer#137]
**Describe the bug**
I'm behind a proxy, and it seems that I am unable to retrieve devices.

**To Reproduce**
1. Start application
2. Click on the 'Refresh' toolbar button
3. See error

**Expected behavior**
I would expect to see the retrieved devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/51745092/67484645-cd207980-f668-11e9-8344-06a9c1383d76.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - OS Version: 1809
 - App version: 0.10.6

**Comment by YingXue** [comment]
Hi there,
Is your proxy blocking the azure traffic? Can you help verify if you can use azure portal to access your devices?

**Comment by mattias-kindborg-axis-communications** [comment]
Hi YingXue!

All other network connections are working fine, here is a snapshot of Edge showing Azure portal.

![image](https://user-images.githubusercontent.com/51745092/67549900-95b3da80-f705-11e9-950c-0ee91a779436.png)

**Comment by mattias-kindborg-axis-communications** [comment]
It seems that I am wrong, it has nothing to do with the proxy :-( I'll close this issue since it is incorrect.
