### ISSUE TITLE
[BUG] Connecting to the public preview company repository

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/azure-iot-explorer#138]
**Describe the bug**
I'm testing the public preview of IoT PnP, and have been reading [the documentation](https://docs.microsoft.com/en-us/azure/iot-pnp/). Azure IoT explorer is mentioned [here](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device#install-the-azure-iot-explorer), but when I try to connect to the repository I get an error.

**To Reproduce**
1. Start application
2. Enter the connection string, as described [here](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device#get-the-connection-string-for-your-company-model-repository)
3. Click on the 'Refresh' toolbar button

**Expected behavior**
I would expect to see the retrieved devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/51745092/67484645-cd207980-f668-11e9-8344-06a9c1383d76.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - OS Version: 1809
 - App version: 0.10.6

**Comment by andrew-buckley** [comment]
Hi @mattias-kindborg-axis-communications. I'm wondering if you can check to see if there is any helpful information in the console/network logs `Help -> Toggle Developer Tools`.

**Comment by mattias-kindborg-axis-communications** [comment]
![image](https://user-images.githubusercontent.com/51745092/67660402-03a70e80-f95f-11e9-9970-b531d23135b9.png)

**Comment by YingXue** [comment]
From the screenshot above, I am guessing the connection string of the hub could be wrong, can you make sure if you copied the right connection string from portal?
You can copy it from: Azure Portal -> Your iot hub -> select 'Shared access policies' from the menu, and choose one policy that has the right permission:
![image](https://user-images.githubusercontent.com/5489222/67712735-cacc6100-f981-11e9-9a74-483bfcfe6ac6.png)

**Comment by mattias-kindborg-axis-communications** [comment]
[The documentation](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device#get-the-connection-string-for-your-company-model-repository) tells me to copy the connection string from the public preview of the _Azure Certified for IoT portal_, not the IoT Hub.

![image](https://user-images.githubusercontent.com/51745092/67752234-f2c7cd00-fa32-11e9-8986-5860c5a8e355.png)

**Comment by andrew-buckley** [comment]
That section in the documentation you are referring to does ask you to find the company model repository connection string in the Azure Certified for IoT portal portal. However it doesn't ask you to use the repository connection string yet. In [this section](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device#use-the-azure-iot-explorer-to-validate-the-code) it describes using the Azure IoT explorer. It asks to use your **IoT Hub connection string** in the App Configuration page when opening the Azure IoT explorer in steps 1 and 2. And then it asks you to use your **repository connection string** in steps 4 and 5.

**Comment by andrew-buckley** [comment]
[This section](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device#prepare-an-iot-hub) talks about getting your IoT Hub connection string. Alternatively you can follow the steps @YingXue described above.

**Comment by mattias-kindborg-axis-communications** [comment]
The error message was better, I've verified that it works. Thanks!
