### ISSUE TITLE
[BUG] Failed to retrieve device list. It is possibly due to an invalid IoT hub connection string

### ISSUE THREAD

**Issue by tsmuthu** [Azure/azure-iot-explorer#142]
**Describe the bug**

**To Reproduce**
1. install the Azure.IoT.explorer.0.10.7.msi 
2. Provide the IoT hub connection string and click on Connect
3. See error popup saying "Failed to retrieve device list. It is possibly due an invalid IoT hub connection string" also available in the Notification panel

**Expected behavior**
The connection to the IOThub need to establish and should display the device details.

**Screenshots**
![image](https://user-images.githubusercontent.com/20000604/67958173-bbb50f80-fc1c-11e9-89c1-8f5e5fa09025.png)

**Desktop (please complete the following information):**
 -  OS: [Windows 10]
 -  OS Version 1703

**Comment by andrew-buckley** [comment]
Hi @tsmuthu, Have you verified that your IoT Hub connection string is valid? Can you also check your IoT Hub in the Azure Portal to see if you have exhausted your message quota?

**Comment by tsmuthu** [comment]
Yes the old desktop version 

https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer

**Comment by andrew-buckley** [comment]
Can you try creating a new shared access key and using the connection string created with that new key? Can you also tell me what tier IoT Hub are you using?

**Comment by tsmuthu** [comment]
Yes. Regenerated the new Primary key and still the same issue. We have F1, S1 and S2 tiers but It still failed to establish the connection for all the tiers

**Comment by andrew-buckley** [comment]
And does this key have the necessary permissions set? Is this reproducible across different machines?

**Comment by tsmuthu** [comment]
Yes, one of my friend is using the same IOThub Connection string.

**Comment by andrew-buckley** [comment]
Ah okay. Can you tell me what permissions you have set on this key?

**Comment by YingXue** [comment]
Hi @tsmuthu 
We are not able to repro this issue unfortunately. 
Can you help us verify a few things?
1. On the login page, verify if you can choose "Add a new connetion string" from the dropdown
2. If you can create a brand new hub, and copy paste the connection string of 'iothubowner' that would be best
Or if you can uninstall this version, reinstall the previous version that worked for you, and re-verify if you can still login in use the connection string you have handy. and then install this new version, verify if it still doesn't work
3. We can probably rule out the persmission being the issue here, as if that's the case you would able to see a error with 'IotHubUnauthorizedAccess;Unauthorized'
4. Lastly, you can open help => toggle developer tool from the menu bar, switch to network tab, and check if you got more specific error

**Comment by tsmuthu** [comment]
Sorry for the delayed response..

As Suggested, i have created a brand new IOTHub with S1 pricing tier and used the iothubowner connection string. I have tried the same in both Azure.IoT.explorer.0.10.6 and 0.10.7. still getting the same error.

**Error on 0.10.7**

![image](https://user-images.githubusercontent.com/20000604/68018704-d3919f80-fcbf-11e9-9379-f841f8e541f9.png)

**Error ON 0.10.6**

![image](https://user-images.githubusercontent.com/20000604/68019000-8c57de80-fcc0-11e9-972d-210b395934cb.png)

**Response from the old desktop version of the device Explorer** 

![image](https://user-images.githubusercontent.com/20000604/68019103-dd67d280-fcc0-11e9-8560-5a29057eee05.png)

**Comment by andrew-buckley** [comment]
Another suggestion is to check your network settings to see if your machine is blocking/restricting traffic to localhost

**Comment by tsmuthu** [comment]
Yes. Check all cant see any issue with the network block. tried using various network providers. Is the issue reported only by me. 

Is it possible to provide the  permission ruled out version to check whether it works.

**Comment by YingXue** [comment]
Hi @tsmuthu 
Any version would get you a more detailed error if the permission is wrong. You can easily verify that by using a different connection string which doesn't have registry read or write.
So far, seems like you are the only lucky user who is having this issue.

**Comment by tsmuthu** [comment]
Also have tried the other connection string which doesn't have the registry read or write permission the error message is same.. **"Failed to retrieve device list. It is possibly due an invalid IoT hub connection string".**

A colleague of mine is also facing the same issue.

**Comment by YingXue** [comment]
Hi @tsmuthu 
Have you tried to check if something else is using the port 8081?
You can do so by running command "netstat -ano" in powershell, and get the PID of the process:
![image](https://user-images.githubusercontent.com/5489222/68234001-37b0ae00-ffb5-11e9-84ab-9e992f8a7a54.png)
Then in your task manager, try to find the PID and see if it is running node.exe 
![image](https://user-images.githubusercontent.com/5489222/68234062-5747d680-ffb5-11e9-99a9-44912d98ee02.png)
If you company has anything to block the local host traffic, you may have to go back and use the old device explorer or wait til we have a hosted version of this tool, which would launch early next year.

**Comment by Joehannus** [comment]
I'm getting the same error. Moving back to the old deprecated application.

**Comment by YingXue** [comment]
Hi @Joehannus ,
If you'd like to give this app another try, do you mind try build it locally and see if it works for you? You can find the instruction which is pretty straightforward in the readme here https://github.com/Azure/azure-iot-explorer/blob/master/README.md#run-it-locally-and-build-it-yourself (step 1 to 4) and see if you can use it in this way. If so, you can also choose to proceed step 5.

**Comment by YingXue** [comment]
If you have any proxy settings enabled, the app may not work properly. We need to know a bit more about the proxy in able to help, but there are two simples things to check here which may resolve the issue:
1.	If the proxy setting is blocking certain sites’ traffic,  please allow http://127.0.0.1:3000 which is where the app is running behind the scene.
2.	The explorer is running a node server locally at http://127.0.0.1:8081, please check if any setting is blocking it.

**Comment by Fike-Rehman** [comment]
Getting exact same error when when I come on to the app or refresh the device list. Have downloaded and tried different releases of the app. Checked my firewall settings, ports etc. as described above. Nothing seems to help.

**Comment by YingXue** [comment]
@Fike-Rehman  I am reopening the bug and we will take a look.

**Comment by YingXue** [comment]
Hi @Fike-Rehman 
After looking into this issue again, we are able to repro the issue in a specific condition, which is when port is 8081 localhost (127.0.0.1) is taken or blocked by some other process.
Can you help verify if anything is using or blocking this port?

**Comment by YingXue** [comment]
Hi @Fike-Rehman @tsmuthu @Joehannus  
We have released a new version too address the issue: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.13.     
If you happen to have other processes using the port this app is trying to use, you would run into this error.
The instructions and link are provided in the error message when this situation happens, and here is also the wiki link for you reference: https://github.com/Azure/azure-iot-explorer/wiki/FAQ#how-to-solve-port-is-in-use
Please feel free to re-open the issue if it didn't solve your problem. Also, we are planning to look into this issue a bit more later to help our users avoid this manual step altogether.
