### ISSUE TITLE
[Feature request] Have a button to select all devices in the list

### ISSUE THREAD

**Issue by anthonyvercolano** [Azure/azure-iot-explorer#144]
I want to search for all devices that start with the string '0000'.  Once I get them I want to select every device and delete them all.  So that if I have 300 devices that start with 0000 I can delete all of them with one operation.

Right now there is now way to select all of the search results.

**Comment by YingXue** [comment]
Hi @anthonyvercolano 
The UI grid compoent that we are using provides a relatively hidden select all experience by default. You can select all by click the mouse while dragging it, similar to how you would use the snipping tool. 
FYI: a PR is also underway to bump device list to 100 at a time. When it's release, you can use it to select a bit devices a time.

**Comment by YingXue** [comment]
Hi @anthonyvercolano 
The new release has implemented the select all experience. Please give it a try: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.10
Please keep in mind that, the select all only select the devices on the current page.
