### ISSUE TITLE
Adjust the number of devices that are loaded by default

### ISSUE THREAD

**Issue by jebrando** [Azure/azure-iot-explorer#145]
It would be nice to change the number of device that is returned on the device list.  I'd like to see 50 devices at a time.

If possible also show the number of devices

**Comment by YingXue** [comment]
Hi @jebrando 
PR is in place to bump device list to 100 at a time. When it's merged you would be able to pull the lasted bits: https://github.com/Azure/azure-iot-explorer/pull/149/files

**Comment by YingXue** [comment]
Closing the issue as the number of devices has been bumped up to 100. In the future we are planning to make the number configurable.
