### ISSUE TITLE
[Feature request] List import & export

### ISSUE THREAD

**Issue by hanabi1224** [Azure/azure-iot-explorer#166]
It will be awesome to have the functionality to export and import devices. 
e.g. Migrate devices from a test hub (Free tier which cannot upgrade) to a prod hub(standard tier)

**Comment by YingXue** [comment]
Hi @hanabi1224 
Thank you for the kind suggestion. We will consider looking into this in the future. Currently it is out of the scope of this tool.
Just in case you are looking for the way to do it, here is the article: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-bulk-identity-mgmt

**Comment by digimaun** [comment]
@hanabi1224  Just want to point out you can use Azure CLI and the [IoT extension](https://github.com/Azure/azure-iot-cli-extension) to do import/export devices.

**Comment by hanabi1224** [comment]
@digimaun Awesome, thank you so much!
