### ISSUE TITLE
[Feature request] Generate SAS for module identity

### ISSUE THREAD

**Issue by anthonyvercolano** [Azure/azure-iot-explorer#200]
**Is your feature request related to a problem? Please describe.**
I would like to easily generate Shared Access Signatures for module identity in the same way that I can generate them for device identity

**Describe the solution you'd like**
I would like it to look exactly the same as the device identity generation of Share Access Signatures.

**Comment by YingXue** [comment]
Hi @anthonyvercolano 
We will look adding this feature soon. Meanwhie please use our CLI extension which already provides this functionality: https://github.com/Azure/azure-iot-cli-extension

**Comment by YingXue** [comment]
#225 is out for review. Will merge and release with the feature added.

**Comment by YingXue** [comment]
@anthonyvercolano 
The latest bits has been release: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.15
