### ISSUE TITLE
[Feature request]: Unable to see any module twin properties in module twin with latest release for iot edge module twins

### ISSUE THREAD

**Issue by initmahesh** [Azure/azure-iot-explorer#203]
Using the latest release cannot see any module twin for ot edge modules.
Is there a plan to add support for edge module twin in Azure Iot Explorer.

so that we can update Iot Edge module twin from the tool.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YingXue** [comment]
Hi,
The latest release only contains module identity which is a non-edge device related feature. There are plans to support edge but it's a bit further down the road.
