### ISSUE TITLE
[Feature request] After successful deletion of 1 or more device, selection must be reset

### ISSUE THREAD

**Issue by kartben** [Azure/azure-iot-explorer#208]
Currently if one deletes say device #2 and #4 in the list of devices, then after deletion item #2 and #4 are still selected.
Expected behaviour: reset selection if delete operation was successful.

**Comment by YingXue** [comment]
@kartben sure we will address this issue in the next release.

**Comment by YingXue** [comment]
Hi @kartben ,
Thank you for your kind suggestion, and it has been addressed in our new release: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.13. 
Please give it a try if you'd like.
