### ISSUE TITLE
[BUG] Disabling a device fails

### ISSUE THREAD

**Issue by jebrando** [Azure/azure-iot-explorer#214]
**Describe the bug**
I try to disable a device in the Device Identity page results in the error:

Failed to update device tpm_device: Error: ErrorCode:DeviceAlreadyExists;A device with ID 'tpm_device' is already registered.

**To Reproduce**
1. Select a Device on the Device list page
2. In the Device Identity page Click the Connect this device to IoT hub button
3. Click the Save button at the top of the pane
4. Error notification comes up

**Desktop (please complete the following information):**
 - OS: Linux
 - OS Version Ubuntu: 18.04
 - App version: 0.10.12

**Comment by YingXue** [comment]
Hi @jebrando 
The fix has just been checked in to the master branch. If you don't mind pull down the lastest master to give it a try.
We will have the fix in the next release.
