### ISSUE TITLE
[BUG] No quit option on macOS in the menu or from cmd+q

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-iot-explorer#217]
**Describe the bug**

On macOS, there is no Quit option in the app menu, nor does cmd+q work to quit the app. You can only quit by cmd+clicking the dock icon and selecting Quit.

**To Reproduce**
1. Install the app on macOS
2. Launch it
3. Try to quit

**Expected behavior**
There should be a Quit menu option in the app menu with an appropriate shortcut of cmd+Q. See https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/#app-menu

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: Catalina
 - App version: 0.10.13

**Comment by YingXue** [comment]
Hi @jimbobbennett 
Thank you for reporting the issue, we will take a look into this.

**Comment by YingXue** [comment]
#224 has been merged to master. Will release the fix in a week or so.
