### ISSUE TITLE
Issue reading from free IOT Hub tier? 

### ISSUE THREAD

**Issue by ms-vincent** [Azure/azure-iot-explorer#218]
It appears that you can't use IoT Explorer to read telemetry from a free scale IoT Hub? I tried connecting a simulated device to a free Hub and used the explorer to view incoming telemetry but it sits there waiting for events indefinitely. When connecting the same simulator to an S1 Hub, telemetry comes flying in. 

![image](https://user-images.githubusercontent.com/16802088/74272576-dfd4c200-4cdc-11ea-9e02-409eb8a2962b.png)

I'm running the latest version: 0.10.12

**Comment by YingXue** [comment]
Hi @ms-vincent 
The tool doesn't differentiate its behavior based on hub tier. 
The issue that you run into might be related to the limit of listeners allowed, as we are retrieving events from even hub, and this article may help you: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups.

**Comment by ms-vincent** [comment]
Thanks for the response @YingXue . That's what I thought about the free vs paid tiers as well. 

I'm aware of the limits of listeners. My scenario is super basic and I've only got one reader which is configured to a consumer group I called "monitor".  You can see the configuration in my screenshots below.
**Consumer Groups**
![image](https://user-images.githubusercontent.com/16802088/74361971-ce9bbc00-4d95-11ea-890e-c167de4bfb35.png)

I used the RPi web simulator with the connection string set to my device: https://azure-samples.github.io/raspberry-pi-web-simulator/
![image](https://user-images.githubusercontent.com/16802088/74362912-82ea1200-4d97-11ea-96b5-47dfd647ce85.png)

and I changed the CG to the "monitor" one that I added: 
![image](https://user-images.githubusercontent.com/16802088/74362881-749bf600-4d97-11ea-9b62-be4ce19c677a.png)

This was initially pointed out by a customer and I was able to replicate it in my own environment.

**Comment by ms-vincent** [comment]
Hi @YingXue any thoughts on this? I don't think this is related to consumer groups.

**Comment by YingXue** [comment]
Hi @ms-vincent 
We are not quite sure what's happening here, and we are not able to repro this issue yet. I would recommend try using our CLI 'monitor-event' command to verify if you are able to get the messages from the hub or not: https://github.com/Azure/azure-iot-cli-extension

**Comment by ms-vincent** [comment]
HI @YingXue, I created a new free hub and doesn't appear as though I'm experiencing the issue anymore. Not sure what was wrong with my customer or my own hub but appears as though it's resolved now so we can just keep this issue closed. Thanks for your responses!
