### ISSUE TITLE
Q: Does viewing Telemetry only work if telemetry is routed to the "events" built in endpoint?

### ISSUE THREAD

**Issue by damiandiaz76** [Azure/azure-iot-explorer#227]
I configured my iot hub to route telemetry messages to a custom endpoint.  This endpoint is an event hub in the same subscription.  Does iot explorer support viewing these messages?

**Comment by YingXue** [comment]
Hi @damiandiaz76 
You observation is absolutely correct.
Azure IoT explorer only retrieves telemetry from its default event hub
The reason being users login through hub connection string, not AAD, so this tool doesn't have access to the route/endpoint related APIs, not to mention users subscriptions.
If you think this feature is helpful, I'd like to know if you would be ok to input the connection string to your event hub. If it is acceptable, please feel free to create a feature request, and we can look into implementing it.
