### ISSUE TITLE
Add support for viewing telemetry routed to a custom endpoint

### ISSUE THREAD

**Issue by damiandiaz76** [Azure/azure-iot-explorer#228]
Currently, the "Telemetry" tab views events sent to the built in endpoint "events".  I configured message routing to route telemetry events to a different event hub.  It would be nice to be able to see my routed telemetry events in explorer.

**Comment by YingXue** [comment]
Hi @damiandiaz76 
The new release is out with this feature support, please give it a try and let us know if it doens't work for you: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.16

**Comment by damiandiaz76** [comment]
I tried the custom event hub feature.  It started to "Receiving... events" but when events came in, the right side window closed. 
<img width="1195" alt="Screen Shot 2020-04-15 at 4 45 46 PM" src="https://user-images.githubusercontent.com/19311187/79396203-9b61de80-7f38-11ea-9bf4-2592e4c8752b.png">

**Comment by damiandiaz76** [comment]
Looks like starting with build 0.10.15, telemetry from the built in endpoint also behaves the same way: when events come in, the telemetry closes.
