### ISSUE TITLE
[BUG] MacOS error: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jeanmarcalkazzi** [Azure/azure-iot-explorer#234]
**Describe the bug**
The latest release for MacOS does not start due to a signature error.

**To Reproduce**
1. Download release 0.10.15
2. Open it
3. 💥

**Expected behavior**
Expected the app to actually open and be usable.

**Desktop (please complete the following information):**
 - OS:   **Mac OS X 10.15.3 (19D76)**
 - App version   **0.10.15**

**Additional context**

```
Process:               Azure IoT explorer [1396]
Path:                  /Applications/Azure IoT explorer.app/Contents/MacOS/Azure IoT explorer
Identifier:            com.microsoft.azure.iot.pnp.ui
Version:               0.10.15 (0.10.15.20200225.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Azure IoT explorer [1396]
User ID:               501
....
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x00003e5498082040
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

**Comment by YingXue** [comment]
We've updated our deployment infra due to a removal of a Macbook images from our dependency team. 
I will delete the 0.10.15 asset from the release tab for now and update the thread when a workable version is added.
Sorry for the inconvenience it has caused.

**Comment by YingXue** [comment]
The release has been uploaded with the new installer: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.15
Please give it a try.
