### ISSUE TITLE
Direct method there is no output window 

### ISSUE THREAD

**Issue by nainesh72** [Azure/azure-iot-explorer#238]
Hi
if we give direct method command where is output of direct method commad
like list of application install on device ?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YingXue** [comment]
Hi @nainesh72 
Can you elaborate a bit more? 
Currently the ui surfaces the result through notification, where you can see a pop up, as well as if you click on 'Notificaiton' from the top right, you can see the history.
Are you referring to something else that we missed?

![image](https://user-images.githubusercontent.com/5489222/77098908-58abf580-69d0-11ea-8a6a-32557b699cc6.png)

**Comment by nainesh72** [comment]
Hi thanks for replay now i tole what is realy my problem i use DM Client on my RB
When i use direct method form azure portal it give result for example i give below command on direct method 
GetInstalledUwpAppsCmd
{
    "__meta": {
        "serviceInterfaceVersion": "1.0.0"
    }
}
it give me list of install application on my RB like this in Result box
{"installedApps":[{"pkgFamilyName":"IoTUAPOOBE_cw5n1h2txyewy","version":"1.0.0.0"},{"pkgFamilyName":"Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy","version":"1000.17763.107.0"},{"pkgFamilyName":"InputApp_cw5n1h2txyewy","version":"1000.17763.107.0"},.....
but i use this command on new device explorer there in no output window and it also not show in notification also
nainesh

**Comment by nainesh72** [comment]
> Hi @nainesh72
> Can you elaborate a bit more?
> Currently the ui surfaces the result through notification, where you can see a pop up, as well as if you click on 'Notificaiton' from the top right where you can see the history.
> Are you referring to something else that we missed?
> 
> ![image](https://user-images.githubusercontent.com/5489222/77098908-58abf580-69d0-11ea-8a6a-32557b699cc6.png)

Hi thanks for replay now i tole what is realy my problem i use DM Client on my RB
When i use direct method form azure portal it give result for example i give below command on direct method
GetInstalledUwpAppsCmd
{
"__meta": {
"serviceInterfaceVersion": "1.0.0"
}
}
it give me list of install application on my RB like this in Result box
{"installedApps":[{"pkgFamilyName":"IoTUAPOOBE_cw5n1h2txyewy","version":"1.0.0.0"},{"pkgFamilyName":"Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy","version":"1000.17763.107.0"},{"pkgFamilyName":"InputApp_cw5n1h2txyewy","version":"1000.17763.107.0"},.....
but i use this command on new device explorer there in no output window and it also not show in notification also
nainesh

**Comment by digimaun** [comment]
Hi @nainesh72 , are you able to try using the [azure-iot extension](https://github.com/Azure/azure-iot-cli-extension#installation) for Azure CLI? [Invoke method is there](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/hub?view=azure-cli-latest#ext-azure-iot-az-iot-hub-invoke-device-method), and I am wondering if the output you desire is available there (as well as portal). Just trying to make sure we understand what you are looking for.

Here is an example for bash (note payload format will be a bit different based on your shell):

`az iot hub invoke-device-method --device-id MyDevice --hub-name MyIoTHub --method-name GetInstalledUwpAppsCmd --method-payload '{"_meta": {"serviceInterfaceVersion": "1.0.0"}}'`

**Comment by nainesh72** [comment]
This thing I do form device explorer current I do from azure portal

[cid:image001.png@01D5FDF6.B4BEE850]
[cid:image002.png@01D5FDF6.CEEEB430]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by digimaun** [comment]
Ok, so if I understand correctly - when you try invoking a device command in IoT explorer, there is no notification like the screenshot @yingxue provided? And you can't see the result in the notification history?

**Comment by YingXue** [comment]
Hi @nainesh72 
Can you share a screenshot of what you are seeing instead using iot explorer? You may have already included two png but we are not able to see it.
I just did a test with my simulated device, and I am seeing the response not being properly parsed and shows [object object] which is a bug would be fixed, but if not, i'd like to know what kind of notification are you seeing.
![image](https://user-images.githubusercontent.com/5489222/77126756-73e62780-6a07-11ea-980e-11363462fd25.png)

**Comment by nainesh72** [comment]
> Hi @nainesh72
> Can you share a screenshot of what you are seeing instead while using iot explorer? You may have already included two png in the earlier comment but we are not able to see it.
> I just did a test with my simulated device, and I am seeing the response not being properly parsed and shows [object object] which is a bug would we are fixing. If this is not the same issue that you are ssing, please include a screenshot of what you see to help us identity the issue.
> 
> Before the fix:
> ![image](https://user-images.githubusercontent.com/5489222/77126756-73e62780-6a07-11ea-980e-11363462fd25.png)
> After the fix:
> ![image](https://user-images.githubusercontent.com/5489222/77127447-bc9ee000-6a09-11ea-9511-84d9435ffad5.png)
> The above fix has not been released yet, but will be soon.

Hi
can i share my pc and show how you my proble
nainesh
346-901-0770

**Comment by YingXue** [comment]
Hi @nainesh72 
A screenshot should be sufficent here. I think if you directly reply to the github email, your screenshot won't show up properly. Please click the link through email and reply on the github site, that would work.
And you may want to remove your number from the site in case of spam.

**Comment by nainesh72** [comment]
> Hi @nainesh72
> A screenshot should be sufficent here. I think if you directly reply to the github email, your screenshot won't show up properly. Please click the link through email and reply on the github site, that would work.
> And I've removed number from the site in case of spam.

Hi u get my screen short nainesh

**Comment by YingXue** [comment]
Hi @nainesh72 
I've got them. So we were talking about the same problm here as you are seeing '[object object]'. The fix #239 is merged into master, and will be release soon. I will update the thread once its out.

**Comment by nainesh72** [comment]
> Hi @nainesh72
> I've got them. So we were talking about the same problm here as you are seeing '[object object]'. The fix #239 is merged into master, and will be released soon. I will update the thread once its out.

Hi
Thank after update #239 can u bild msi file please so i download

**Comment by nainesh72** [comment]
Hi
Thanks for Replay Can we build or hava code that this application in C# MVC


Thanks
Nainesh
346-901-0770

________________________________
From: Nainesh Suthar <nsap72@hotmail.com>
Sent: Thursday, March 19, 2020 2:01 PM
To: Azure/azure-iot-explorer <reply@reply.github.com>
Subject: RE: [Azure/azure-iot-explorer] Direct method there is no output window (#238)


This thing I do form device explorer current I do from azure portal



[cid:image001.png@01D5FDF6.B4BEE850]

[cid:image002.png@01D5FDF6.CEEEB430]



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nainesh72** [comment]
Thanank YingXue now it work

**Comment by nainesh72** [comment]
Hi
I need some help can help me

Thanks
Nainesh
346-901-0770

________________________________
From: Nainesh Suthar <nsap72@hotmail.com>
Sent: Thursday, March 19, 2020 2:01 PM
To: Azure/azure-iot-explorer <reply@reply.github.com>
Subject: RE: [Azure/azure-iot-explorer] Direct method there is no output window (#238)


This thing I do form device explorer current I do from azure portal



[cid:image001.png@01D5FDF6.B4BEE850]

[cid:image002.png@01D5FDF6.CEEEB430]



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
