### ISSUE TITLE
Enable Direct method on Module Identity 

### ISSUE THREAD

**Issue by nainesh72** [Azure/azure-iot-explorer#245]
Hi
I have One Device and in that device on Module, Now i want to give direct method on Module Identity
Hove i give because there no option for direct method, like on device where on portal we have option for direct method 
Nainesh
![test1](https://user-images.githubusercontent.com/50742468/77766369-8c5cd000-700d-11ea-9216-d030bbabc7fc.PNG)

**Comment by YingXue** [comment]
Hi @nainesh72 
This is in our backlog, and we will look into this a bit later.

**Comment by YingXue** [comment]
Hi @nainesh72 
I will keep this issue open so we can keep track of it

**Comment by YingXue** [comment]
Feature has been released: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.13.3
