### ISSUE TITLE
Telemetry window closes when events come in.

### ISSUE THREAD

**Issue by damiandiaz76** [Azure/azure-iot-explorer#257]
**Describe the bug**
When viewing telemetry for a device, the telemetry view closes when an event arrives.  This works fine in 0.10.14.

**To Reproduce**
1. Search for and select device.
2. Click on 'Telemetry'
3. Click on 'Start'
4. When event comes in, the right hand side of the window closes.

**Expected behavior**
A display stream of events is shown.

**Screenshots**
<img width="1195" alt="Screen Shot 2020-04-15 at 4 45 46 PM" src="https://user-images.githubusercontent.com/19311187/79403138-48455700-7f4b-11ea-97ca-597c7e73ad01.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - OS Version: 10.15.4
 - App version 0.10.15 and 0.10.16 (works in 0.10.14)

**Comment by YingXue** [comment]
hi @damiandiaz76 please avoid use this feature at this point. The event hub sdk had the entity path/event hub name specified as optional paratemeter, but after digging a bit more, it is required in order to retreive events. 
We will need to add another input for users to input this piece of info before we can enable this feature. 
Sorry for the incovenience.

**Comment by YingXue** [comment]
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.18 
Latest release has been published to address this issue.
Closing.

**Comment by damiandiaz76** [comment]
I still see this issue on Version 0.10.18 (0.10.18.20200506.1).

**Comment by YingXue** [comment]
@damiandiaz76 Were you able to input both event hub connection string and event hub?

**Comment by damiandiaz76** [comment]
1. Yes
2. It happens with a custom event hub and with the built in endpoint.
3. Yes

It appears to me that the connection gets established. Have you tried running the "Telemetry" screen, clicked "Start" and then sent a telemetry message from the connected device?  Once the message comes in, that's when I see the screen close.

**Comment by YingXue** [comment]
@damiandiaz76 
Yes, and I am able to see it fine. Some steps that may help here.
1. Click help -> toggle developer tools, and check if the network tab has made an api call 'monitor'.
![image](https://user-images.githubusercontent.com/5489222/81611806-8f7b0800-9390-11ea-9fcf-13662e5ec54c.png)
Check if the highlighted parameters are present
2. Check if you are seeing the response 
![image](https://user-images.githubusercontent.com/5489222/81611876-b33e4e00-9390-11ea-9b10-50d9783ac99c.png)
3. If both of them shows correctly, check if there is vertial scroll bar somewhere on the app, maybe some unexpected response has messed up with the style and push the right side of the app down.

**Comment by damiandiaz76** [comment]
1. The connection parameters are present.
2. I do see the response come in.
3. I can't find any scroll bars in the app.

Here's an example response I'm getting with several messages.  Some of the properties have escaped json strings intentionally:

[{"body":{"version":1162,"properties":{"reported":{"host":"1ef13bef0036","pip":"73.78.223.139","$metadata":{"$lastUpdated":"2020-05-11T21:59:41.6704399Z","host":{"$lastUpdated":"2020-05-11T21:59:41.6704399Z"},"pip":{"$lastUpdated":"2020-05-11T21:59:41.6704399Z"}},"$version":63}}},"enqueuedTime":"2020-05-11T21:59:41.922Z","properties":{"hubName":"ddiaz-iot-iothub-westus2","deviceId":"sampledevice","operationTimestamp":"2020-05-11T21:59:41.6704399+00:00","iothub-message-schema":"twinChangeNotification","opType":"updateTwin","siteUUID":"$twin.tags.siteUUID","deviceinit":"$twin.tags.deviceinit","networkinfo":"{\"data\":{\"802.1xStatus\":\"false\",\"cdpStatus\":\"NA\",\"connectionMode\":\"half-duplex\",\"connectionSpeed\":\"1000Mbps\",\"connectionType\":\"eth0\",\"dnsAlternativeAddress\":\"\",\"dnsDomain\":\"polycom.com\",\"dnsPrimaryAddress\":\"10.223.10.1\",\"eapMethod\":\"PEAP\",\"ipv4Address\":\"10.223.75.46\",\"ipv4AddressSource\":\"manual\",\"ipv4Gateway\":\"10.223.75.253\",\"ipv4Subnet\":\"255.255.255.0\",\"ipv4Vlan\":\"1\",\"ipv6AddressSource\":\"NA\",\"ipv6GlobalAddress\":\"NA\",\"ipv6LinkLocalAddress\":\"NA\",\"ipv6ULA\":\"NA\",\"lldpLocationInformation\":\"NA\",\"lldpNeighbors\":\"NA\",\"lldpStatus\":\"active\",\"ntpServer\":\"Auto\",\"pcPortStatus\":\"NA\",\"provisioningProtocol\":\"HTTPS\"},\"rto\":\"15\",\"type\":\"ni\"}","roomUUID":"fs","primarydeviceinfo":"{\"data\":{\"hardwareModel\":\"nodejs\",\"hardwareRevision\":\"7\",\"macAddress\":\"00:aa:bb:cc:dd:ee\",\"manufacturer\":\"Polycom\",\"offsetGMT\":\"-06:00\",\"productFamily\":\"G7500\",\"serialNumber\":\"sampledevice\",\"softwareBuild\":\"212128\",\"softwareRelease\":\"3.0.1\"},\"rto\":\"15\",\"type\":\"pdi\"}","tenantUUID":"t","devicepip":"73.78.223.139","devicemetadata":"{\"deviceName\":\"Mo PolyOS 3.1.1\"}"}},{"body":{"name":"UPLOAD_INLINE","type":"request","frameId":"frameId","payload":{"data":{"hardwareModel":"nodejs","hardwareRevision":"7","macAddress":"00:aa:bb:cc:dd:ee","manufacturer":"Polycom","offsetGMT":"-06:00","productFamily":"G7500","serialNumber":"sampledevice","softwareBuild":"212128","softwareRelease":"3.0.1"},"rto":"15","type":"pdi"}},"enqueuedTime":"2020-05-11T21:59:42.141Z","properties":{"siteUUID":"$twin.tags.siteUUID","deviceinit":"$twin.tags.deviceinit","networkinfo":"{\"data\":{\"802.1xStatus\":\"false\",\"cdpStatus\":\"NA\",\"connectionMode\":\"half-duplex\",\"connectionSpeed\":\"1000Mbps\",\"connectionType\":\"eth0\",\"dnsAlternativeAddress\":\"\",\"dnsDomain\":\"polycom.com\",\"dnsPrimaryAddress\":\"10.223.10.1\",\"eapMethod\":\"PEAP\",\"ipv4Address\":\"10.223.75.46\",\"ipv4AddressSource\":\"manual\",\"ipv4Gateway\":\"10.223.75.253\",\"ipv4Subnet\":\"255.255.255.0\",\"ipv4Vlan\":\"1\",\"ipv6AddressSource\":\"NA\",\"ipv6GlobalAddress\":\"NA\",\"ipv6LinkLocalAddress\":\"NA\",\"ipv6ULA\":\"NA\",\"lldpLocationInformation\":\"NA\",\"lldpNeighbors\":\"NA\",\"lldpStatus\":\"active\",\"ntpServer\":\"Auto\",\"pcPortStatus\":\"NA\",\"provisioningProtocol\":\"HTTPS\"},\"rto\":\"15\",\"type\":\"ni\"}","roomUUID":"fs","primarydeviceinfo":"{\"data\":{\"hardwareModel\":\"nodejs\",\"hardwareRevision\":\"7\",\"macAddress\":\"00:aa:bb:cc:dd:ee\",\"manufacturer\":\"Polycom\",\"offsetGMT\":\"-06:00\",\"productFamily\":\"G7500\",\"serialNumber\":\"sampledevice\",\"softwareBuild\":\"212128\",\"softwareRelease\":\"3.0.1\"},\"rto\":\"15\",\"type\":\"pdi\"}","tenantUUID":"t","devicepip":"73.78.223.139","devicemetadata":"{\"deviceName\":\"Mo PolyOS 3.1.1\"}"}},{"body":{"name":"UPLOAD_INLINE","type":"request","frameId":"frameId","payload":{"data":{"802.1xStatus":"false","cdpStatus":"NA","connectionMode":"half-duplex","connectionSpeed":"1000Mbps","connectionType":"eth0","dnsAlternativeAddress":"","dnsDomain":"polycom.com","dnsPrimaryAddress":"10.223.10.1","eapMethod":"PEAP","ipv4Address":"10.223.75.46","ipv4AddressSource":"manual","ipv4Gateway":"10.223.75.253","ipv4Subnet":"255.255.255.0","ipv4Vlan":"1","ipv6AddressSource":"NA","ipv6GlobalAddress":"NA","ipv6LinkLocalAddress":"NA","ipv6ULA":"NA","lldpLocationInformation":"NA","lldpNeighbors":"NA","lldpStatus":"active","ntpServer":"Auto","pcPortStatus":"NA","provisioningProtocol":"HTTPS"},"rto":"15","type":"ni"}},"enqueuedTime":"2020-05-11T21:59:42.141Z","properties":{"siteUUID":"$twin.tags.siteUUID","deviceinit":"$twin.tags.deviceinit","networkinfo":"{\"data\":{\"802.1xStatus\":\"false\",\"cdpStatus\":\"NA\",\"connectionMode\":\"half-duplex\",\"connectionSpeed\":\"1000Mbps\",\"connectionType\":\"eth0\",\"dnsAlternativeAddress\":\"\",\"dnsDomain\":\"polycom.com\",\"dnsPrimaryAddress\":\"10.223.10.1\",\"eapMethod\":\"PEAP\",\"ipv4Address\":\"10.223.75.46\",\"ipv4AddressSource\":\"manual\",\"ipv4Gateway\":\"10.223.75.253\",\"ipv4Subnet\":\"255.255.255.0\",\"ipv4Vlan\":\"1\",\"ipv6AddressSource\":\"NA\",\"ipv6GlobalAddress\":\"NA\",\"ipv6LinkLocalAddress\":\"NA\",\"ipv6ULA\":\"NA\",\"lldpLocationInformation\":\"NA\",\"lldpNeighbors\":\"NA\",\"lldpStatus\":\"active\",\"ntpServer\":\"Auto\",\"pcPortStatus\":\"NA\",\"provisioningProtocol\":\"HTTPS\"},\"rto\":\"15\",\"type\":\"ni\"}","roomUUID":"fs","primarydeviceinfo":"{\"data\":{\"hardwareModel\":\"nodejs\",\"hardwareRevision\":\"7\",\"macAddress\":\"00:aa:bb:cc:dd:ee\",\"manufacturer\":\"Polycom\",\"offsetGMT\":\"-06:00\",\"productFamily\":\"G7500\",\"serialNumber\":\"sampledevice\",\"softwareBuild\":\"212128\",\"softwareRelease\":\"3.0.1\"},\"rto\":\"15\",\"type\":\"pdi\"}","tenantUUID":"t","devicepip":"73.78.223.139","devicemetadata":"{\"deviceName\":\"Mo PolyOS 3.1.1\"}"}},{"body":{"version":1163,"tags":{"primarydeviceinfo":"{\"data\":{\"hardwareModel\":\"nodejs\",\"hardwareRevision\":\"7\",\"macAddress\":\"00:aa:bb:cc:dd:ee\",\"manufacturer\":\"Polycom\",\"offsetGMT\":\"-06:00\",\"productFamily\":\"G7500\",\"serialNumber\":\"sampledevice\",\"softwareBuild\":\"212128\",\"softwareRelease\":\"3.0.1\"},\"rto\":\"15\",\"type\":\"pdi\"}"}},"enqueuedTime":"2020-05-11T21:59:42.344Z","properties":{"hubName":"ddiaz-iot-iothub-westus2","deviceId":"sampledevice","operationTimestamp":"2020-05-11T21:59:42.1820355Z","iothub-message-schema":"twinChangeNotification","opType":"updateTwin","siteUUID":"$twin.tags.siteUUID","deviceinit":"$twin.tags.deviceinit","networkinfo":"{\"data\":{\"802.1xStatus\":\"false\",\"cdpStatus\":\"NA\",\"connectionMode\":\"half-duplex\",\"connectionSpeed\":\"1000Mbps\",\"connectionType\":\"eth0\",\"dnsAlternativeAddress\":\"\",\"dnsDomain\":\"polycom.com\",\"dnsPrimaryAddress\":\"10.223.10.1\",\"eapMethod\":\"PEAP\",\"ipv4Address\":\"10.223.75.46\",\"ipv4AddressSource\":\"manual\",\"ipv4Gateway\":\"10.223.75.253\",\"ipv4Subnet\":\"255.255.255.0\",\"ipv4Vlan\":\"1\",\"ipv6AddressSource\":\"NA\",\"ipv6GlobalAddress\":\"NA\",\"ipv6LinkLocalAddress\":\"NA\",\"ipv6ULA\":\"NA\",\"lldpLocationInformation\":\"NA\",\"lldpNeighbors\":\"NA\",\"lldpStatus\":\"active\",\"ntpServer\":\"Auto\",\"pcPortStatus\":\"NA\",\"provisioningProtocol\":\"HTTPS\"},\"rto\":\"15\",\"type\":\"ni\"}","roomUUID":"fs","primarydeviceinfo":"{\"data\":{\"hardwareModel\":\"nodejs\",\"hardwareRevision\":\"7\",\"macAddress\":\"00:aa:bb:cc:dd:ee\",\"manufacturer\":\"Polycom\",\"offsetGMT\":\"-06:00\",\"productFamily\":\"G7500\",\"serialNumber\":\"sampledevice\",\"softwareBuild\":\"212128\",\"softwareRelease\":\"3.0.1\"},\"rto\":\"15\",\"type\":\"pdi\"}","tenantUUID":"t","devicepip":"73.78.223.139","devicemetadata":"{\"deviceName\":\"Mo PolyOS 3.1.1\"}"}},{"body":{"version":1164,"tags":{"networkinfo":"{\"data\":{\"802.1xStatus\":\"false\",\"cdpStatus\":\"NA\",\"connectionMode\":\"half-duplex\",\"connectionSpeed\":\"1000Mbps\",\"connectionType\":\"eth0\",\"dnsAlternativeAddress\":\"\",\"dnsDomain\":\"polycom.com\",\"dnsPrimaryAddress\":\"10.223.10.1\",\"eapMethod\":\"PEAP\",\"ipv4Address\":\"10.223.75.46\",\"ipv4AddressSource\":\"manual\",\"ipv4Gateway\":\"10.223.75.253\",\"ipv4Subnet\":\"255.255.255.0\",\"ipv4Vlan\":\"1\",\"ipv6AddressSource\":\"NA\",\"ipv6GlobalAddress\":\"NA\",\"ipv6LinkLocalAddress\":\"NA\",\"ipv6ULA\":\"NA\",\"lldpLocationInformation\":\"NA\",\"lldpNeighbors\":\"NA\",\"lldpStatus\":\"active\",\"ntpServer\":\"Auto\",\"pcPortStatus\":\"NA\",\"provisioningProtocol\":\"HTTPS\"},\"rto\":\"15\",\"type\":\"ni\"}"}},"enqueuedTime":"2020-05-11T21:59:42.547Z","properties":{"hubName":"ddiaz-iot-iothub-westus2","deviceId":"sampledevice","operationTimestamp":"2020-05-11T21:59:42.3226642Z","iothub-message-schema":"twinChangeNotification","opType":"updateTwin","siteUUID":"$twin.tags.siteUUID","deviceinit":"$twin.tags.deviceinit","networkinfo":"{\"data\":{\"802.1xStatus\":\"false\",\"cdpStatus\":\"NA\",\"connectionMode\":\"half-duplex\",\"connectionSpeed\":\"1000Mbps\",\"connectionType\":\"eth0\",\"dnsAlternativeAddress\":\"\",\"dnsDomain\":\"polycom.com\",\"dnsPrimaryAddress\":\"10.223.10.1\",\"eapMethod\":\"PEAP\",\"ipv4Address\":\"10.223.75.46\",\"ipv4AddressSource\":\"manual\",\"ipv4Gateway\":\"10.223.75.253\",\"ipv4Subnet\":\"255.255.255.0\",\"ipv4Vlan\":\"1\",\"ipv6AddressSource\":\"NA\",\"ipv6GlobalAddress\":\"NA\",\"ipv6LinkLocalAddress\":\"NA\",\"ipv6ULA\":\"NA\",\"lldpLocationInformation\":\"NA\",\"lldpNeighbors\":\"NA\",\"lldpStatus\":\"active\",\"ntpServer\":\"Auto\",\"pcPortStatus\":\"NA\",\"provisioningProtocol\":\"HTTPS\"},\"rto\":\"15\",\"type\":\"ni\"}","roomUUID":"fs","primarydeviceinfo":"{\"data\":{\"hardwareModel\":\"nodejs\",\"hardwareRevision\":\"7\",\"macAddress\":\"00:aa:bb:cc:dd:ee\",\"manufacturer\":\"Polycom\",\"offsetGMT\":\"-06:00\",\"productFamily\":\"G7500\",\"serialNumber\":\"sampledevice\",\"softwareBuild\":\"212128\",\"softwareRelease\":\"3.0.1\"},\"rto\":\"15\",\"type\":\"pdi\"}","tenantUUID":"t","devicepip":"73.78.223.139","devicemetadata":"{\"deviceName\":\"Mo PolyOS 3.1.1\"}"}}]

**Comment by andrerav** [comment]
Still seeing this problem with 10.19 :/

**Comment by ShaneOsborne** [comment]
Can also confirm issue still there in 0.10.19

**Comment by YingXue** [comment]
Hi Folks,
Please try our latest version 0.11.1. (There was no update between the issue report to 0.10.19)
We did a major update on the latest release, and would love to know if it is still happening.
Please feel free to reopen if it is still happening.

**Comment by damiandiaz76** [comment]
I am able to see the events now but there is still a glitch with the left side menu expanding to the right.  I need to scroll the application window to see the events.
<img width="1209" alt="Screen Shot 2020-07-27 at 1 49 31 PM" src="https://user-images.githubusercontent.com/19311187/88585431-53128c00-d010-11ea-8744-80536c2339e5.png">
