### ISSUE TITLE
[BUG] Can't delete multiple devices

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#274]
From the device list there are radio buttons to select multiple devices, I expected to be able to delete multiple with one click, but it fails with: `Failed to delete 1 device(s): Error`

If I delete one by one, it also fails on the second attempt and I need to reconnect to the same hub.

Looks like it only allows to delete one device at a time per hub connection.

**Comment by YingXue** [comment]
This seems like a duplicate issue of #264 which has already been fixed. Please reopen if it is not the same along with more details.
