### ISSUE TITLE
[BUG] How to connect IoT Central with IoT Explorer?

### ISSUE THREAD

**Issue by ahidaka** [Azure/azure-iot-explorer#299]
**Describe the bug**
Hi, I'm developing IoT PnP (Preview) application and devices for IoT Central. I am confused because IoT Explorer cannot be used for IoT Central connections. I know IoT Explorer is new tool for IoT Hub and IoT Central. I know IoT Central IotHub connection string is depreciated, too.

I saw ["issues/21"](https://github.com/Azure/iot-central-firmware/issues/21) and tried use dps-keygen with several options and generate my original connection String for IoT Explorer, but all of them were failed to connect.

The message is always "No devices". The issue is that it is not clear how connect IoT Central with IoT Explorer. Or I'd like to know how to generate Connection String to connect IoT Central.

**To Reproduce**
Typically steps to reproduce the behavior:

1. Use dps-keygen to find **REAL** iothub hostname with registered device Key String.
dps-keygen -di:mxchip-001 -dk:NdYb1+SB1PyiIPutiRJo7h1ZjHgPoxIn2xpt4YOXXXX= -si:0ne0009DXXX

returned;
 HostName=iotc-a8d39dc8-9323-415c-a6de-20d93f4802a6.azure-devices.net;DeviceId=mxchip-001;SharedAccessKey=.......

2. I generated Connection String with above **REAL** iothub hostname, string "SharedAccessKeyName=iothubowner", and SAS Key string from "https://custom-pnp-rpi3.azureiotcentral.com/admin/device-connection".
So my Connection Strings is 
HostName=iotc-a8d39dc8-9323-415c-a6de-20d93f4802a6.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=aFIG4ZZBQvYn8nvTmTN2DQXT4pg5Gk5ufcQzIUhhajlrRsAlLG+Z5BOeAdFZZMV1gS1qaVXXXXXXXXXXXXXXXX==

3. Run IoT Explorer and Input above my generated Connection Strings.

4. No devices found.

**Expected behavior**
Some of registered device will be shown.

**Screenshots**
![IoT Explorer No devices](https://user-images.githubusercontent.com/10113490/83938494-ae45b080-a80f-11ea-9b25-aa0ba637efc2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version:  1909 (Build 18363.836)
 - App version: Version 0.10.18

**Additional context**
None.

**Comment by YingXue** [comment]
Hi @ahidaka 
Will you be able to confirm what permisson that your key contains?
I would recommend using the key that contains 'Registry read'. If you are not sure, you can use Azure portal, and use the connection string of 'iothubowner' policy.

**Comment by ahidaka** [comment]
I already succeeded to connect IoT Hub directly. I just do want to connect with IoT Central.
IoT Central hides the connection string for IoT Hub. I could't find the way to connect IoT Central with IoT Explorer.

**Comment by scout208** [comment]
@ahidaka Did you ever figure this out? I'm trying to do the same thing.

**Comment by rido-min** [comment]
IoT Central does not expose the underlying hub connection details, hence IoTExplorer can't be configured to access the hub apis required.

May I ask what's your intent to use IoTExplorer with Central?

**Comment by scout208** [comment]
I would mainly just like access to the IoT Hub connection string so I can see module logs on my devices, setup IoT Edge simulator for testing new modules, etc.

**Comment by rido-min** [comment]
Thanks @scout28 for your feedback, 

I'd love to learn more about your current scenario with Edge modules. When you said module logs, you mean telemetry sent from modules or [these logs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2020-11#retrieve-module-logs).

>to see what's happening at a lower-level would be really helpful

Which questions would you like to answer getting access to the *lower-level* details?

Today we are suggesting to do most of the Edge module development using Hub and simulator, where you can use tools like IoTExplorer, the az iot CLI or the [VSCode IoT Hub Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) before the modules deploying to Central.

There are also Central APIs that will give you access to low-level messages, eg:
https://docs.microsoft.com/en-us/rest/api/iotcentral/1.0/devices/getmoduletelemetryvalue

/c @sandeeppujar @konichi3

**Comment by scout208** [comment]
I'm talking about the actual logs. I've basically found what you are suggesting. I have my IoT Central application running with all my devices in the field. If I want to develop or update any of the modules however I can't use that IoT Hub to test against because I don't have access to connection strings which means I can't simulate any of them using the tools. Furthermore if I deploy a module out there and it is not working for some reason, I have no way to view the error from the logs which is not helpful for development. So what I have to do is use a separate IoT Hub  and device for development and testing and then push the modules out my IoT Central devices later. 

That's not a big deal but there are sometimes differences between testing and production environments and something could go wrong with a module on the production device that didn't happen on the testing device. For that reason I think it would still be helpful to be able to see the module logs for IoT Central devices. It could even be part of the az iot CLI, but as far as I can tell there's no way to do that at the moment.

**Comment by scout208** [comment]
This may be a separate issue but I have a UWP app running on my IoT Edge devices that acts as a sort of HMI for the device. I want to be able to send device telemetry from the app to to the IoT Hub and view it in IoT Central. The main problem I found with this is since IoT Central uses DPS there is no way for me to know the connection string of my devices and I can't seem to read it from the TPM either (it's always empty) so I have no way of creating a DeviceClient to send the events.

**Comment by rido-min** [comment]
I see, some workarounds/suggestions.

You can get the logs from edge modules by invoking the command [GetModuleLogs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2020-11#retrieve-module-logs) using the azure CLI, and I've exploring an option to provide the [$edgeAgent DTDL model](https://github.com/rido-min/iot-plugandplay-models/blob/edge/dtmi/azure/edgeagent-1.json) with the command definitions, so those can be invoked from IoTExplorer when using Hub, or the Central UI. 

We are looking to improve the IoT developer experience, including troubleshooting, and this kind of feedback is extremely useful, do you mind if we meet 30 mins to better understand your needs and expectations? You can contact me at rmpablos@microsoft.com

**Comment by rido-min** [comment]
BTW, you can get the device connection string when using DPS. Look at the Provisioning Result like [here](https://github.com/ridomin/DeviceClientFactory/blob/master/Rido.DeviceClientFactory/DPS.cs#L83)

**Comment by scout208** [comment]
Okay, thanks. I'll try some of those. I'm also sending you an email now. 👍 I really appreciate the support!

**Comment by scout208** [comment]
Yeah, it seems like I should be able to configure IoT Edge to use an external provisioning service that would allow me to write the connection string to the TPM, it would just be more convenient if the Edge daemon did that for me. I was using the [Azure Device Agent](https://github.com/ms-iot/azure-client-tools/tree/master/docs/device-agent) before and it had that built-in so I didn't have to worry about it.

**Comment by horeich** [comment]
I'd like to continue the conversation here. It's really unconvient not to be able to access the IoT Hub behind IoT central applications.

In my case, I need to update desired properties of a IoT central device which I'm not able to throug the deviceClient API. So I though I use the registryManager API which allows to update desired properties but it **requires an IoT hub connection string**. Where can I find the SharedAccessKey?

**Comment by scout208** [comment]
@horeich Are you talking about the SharedAccessKey for the device or for the iothubowner policy?

**Comment by rido-min** [comment]
>I need to update desired properties of an IoT central device 

@horeich you should use the IoT Central APIs such as: https://docs.microsoft.com/en-us/rest/api/iotcentral/1.0dataplane/devices/update

Note this APIs require AAD tokens and RBAC permissions.

For a general purpose tool to interact with the twins in central: https://github.com/iot-for-all/iotc-twinviewer

**Comment by horeich** [comment]
> @horeich Are you talking about the SharedAccessKey for the device or for the iothubowner policy?

Yes, you're right. The SharedAccessKey for the iothubowner policy

Currently, we use the .NET Azure IoT Hub APIs to have a generic way to access both IoT Central IoT devices + IoT Hub devices (data sent to simple IoT Hub devices is used for third party apps). The deviceClient API allows us to serve both purposes and I'd like to extend the existing microservice to have better access to device info. I'm aware of the REST API but I'm not fully convinced it is a generic way to access my Iot hub devices.

**Comment by rido-min** [comment]
Unfortunately there is no generic API to access Hub and Central. 

One option to implement *that generic way*, would be to use the Hub APIs with RBAC as described [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-dev-guide-azure-ad-rbac). Then you should map both REST APIs.
