### ISSUE TITLE
[Feature request] Installation from chocolatey

### ISSUE THREAD

**Issue by devdeer-stephan** [Azure/azure-iot-explorer#301]
**Is your feature request related to a problem? Please describe.**
I find it tedious to install the Azure IoT Explorer from the github releases. I would love to be able to install it together with most of my other software in a scripted manner from [chocolatey](https://chocolatey.org/).

**Describe the solution you'd like**
I would recommend an automated build that packs the application in a nupkg (which is basically a special form of zip) and uploads it to chocolatey.

**Describe alternatives you've considered**
You could also prepare a download and install script which downloads and executes the setup (i.e. powershell). But it wouldn't be as comfortable and would also lack features like latest or update.

**Comment by montgomp** [comment]
We've engaged with the Chocolatey community to list the package on their service (https://github.com/chocolatey-community/chocolatey-package-requests/issues/870)  and will update this issue when we can get it listed.

**Comment by montgomp** [comment]
This package can be installed via Chocolatey via `choco install azure-iot-explorer --pre`
