### ISSUE TITLE
[BUG] Cannot set arrays in JSON for device twin

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-explorer#305]
Repro:
* Open IoT Explorer 
* Go to a device's twin.
* Attempt to set a desired value containing an array of JSON values.

Expect this to work.
Actual: Fails, with message (presumably from hub) that this isn't supported.

The root issue is IoT Explorer is using an older API_VERSION when connecting to Hub.  You want to be on 2019-10-01 or later and this should just work.

**Comment by YingXue** [comment]
#312 has addressed the issue.

**Comment by YingXue** [comment]
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.19 has just been released.
