### ISSUE TITLE
[BUG] Nearly impossible to copy response from direct method call

### ISSUE THREAD

**Issue by olavt** [Azure/azure-iot-explorer#328]
In the new version of the Device Explorer (Version 0.10.19) it is nearly impossible to copy / paste the response from a direct method call. I typically copy the information from the dialog in order to paste it into JSON LINT (https://jsonlint.com/) in order to be able to make a large JSON response readable. But, in the latest version it is nearly impossible to select / copy the response body when the response is long. It doesn't seem to be possible to select / drag with the mouse to select the text that is not visible. This was very easy with some of the earlier versions where the response was  displayed in an own tab and one could just do CTRL A and copy the whole response text. That doesn't work anymore as that would select all the text in the whole application window.

**To Reproduce**
1. Select a device in Device Explorer
2. Click on "Direct Method"
3. Enter a name of a direct method and invoke it
4. Try to select the response text if the response text is large (does not fit without scrolling)

**Expected behavior**
It should be easy to select / copy all the response text.

**Screenshots**
![Response](https://user-images.githubusercontent.com/3481146/87355533-d4721500-c560-11ea-9474-9ff70c3343fb.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - App version: 0.10.19

**Additional context**

**Comment by YingXue** [comment]
Hi @olavt, were you able to click on the 'notifications' button from the right top, and check if can see the full details there instead?

**Comment by YingXue** [comment]
Hi @olavt 
If you are able to use the work around provided above, we will go ahead and close this issue. We are planning to move alway from this fly out notification pattern in the future anyways. If the workaround is not working for you, please feel free to reopen this issue.

**Comment by olavt** [comment]
Using the Notifications it is still painful to copy / paste the entire text. I found a copy of the IoT Device Explorer and that tool is easier to use.
