### ISSUE TITLE
[BUG] Properties (non-writeable) doesn't display a false value for boolean type

### ISSUE THREAD

**Issue by ryanwinter** [Azure/azure-iot-explorer#341]
**Describe the bug**
For boolean properties, the value is blank when it should be false.

**To Reproduce**
1. Set a read-only property
2. Set the value to false
3. Observe a blank in the value field for the property.

**Expected behavior**
"false" instead of a blank field.

**Screenshots**
![image](https://user-images.githubusercontent.com/10238039/89075143-5f5d5880-d332-11ea-9d9e-f08300e58545.png)

**Desktop (please complete the following information):**
 - Windows
 - 10
 - 0.11.1

**Comment by YingXue** [comment]
Please check out our latest release 0.11.3 which has the fix included. Thank you again for reporting the issue.
