### ISSUE TITLE
[BUG] Telemetry does not display when message property matches Azure IoT Hub routing rule

### ISSUE THREAD

**Issue by bawilless** [Azure/azure-iot-explorer#344]
I have a message route setup in my IoT Hub.  When my device sends a telemetry message with properties set that match my routing rule, the telemetry message is not displayed in the azure-IoT-explorer.  
If I change the routing rule so that it does not match my message property then the message is displayed in the azure-IoT-explorer utility.  

My azure IoT explorer is using the $default Consumer group.  I tried to add and use a custom consumer group and experienced the same issue.

**To Reproduce**
1. Configure a Message route in IoT Hub
2. Set the routing query to (test = 'true')
3. From the IoT Device (I'm using Azure Sphere), set a message property IoTHubMessage_SetProperty(messageHandle, "log", "true");
4. Start the application and trigger it to send telemetry
5. From azure-iot-explorer, select the device and monitor telemetry

{
  "body": {
    "temp": 45.1
  },
  "enqueuedTime": "2020-08-12T15:34:31.410Z",
  "properties": {
    "log": "true"
  }
}

6.  Change the routing query to match the message property (log = 'true')
7.  Telemetry messages are no longer displayed by the azure-iot-explorer telemetry page
8.  Create a new consumer group, change the azure-iot-explorer to use the new consumer group and notice that the behavior described above is repeatable using the new consumer group

**Expected behavior**
I expect to see the telemetry no matter what routing rules are matched, especially when using a new consumer group.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version [0.11.2]

**Comment by YingXue** [comment]
Hi @bawilless 
Explorer only monitoring messages that does not have routing setup, as it is only retrieving messages from the hub's built in endpoints. 
Please refer to our wiki to check the full list of features we support: https://github.com/Azure/azure-iot-explorer/wiki#device-funcitonalities
