### ISSUE TITLE
[Feature request] Define startingpoint of consuming telemetry data

### ISSUE THREAD

**Issue by koepalex** [Azure/azure-iot-explorer#351]
**Is your feature request related to a problem? Please describe.**
In my current testing, there are so many messages send to IoT Hub (ongoing) that IoT Explorer is not able to show results under Telemetry.

**Describe the solution you'd like**
I would like to configure on Telemetry page, what is the starting point to consume IoT Hub messages. In my case the historical messages are unimportant, showing the recent once would be sufficient. 

**Describe alternatives you've considered**
n/a

**Additional context**
Yesterday it took 70min before the first messages were shown in Azure IoT Explorer.

**Comment by YingXue** [comment]
Feature has been released: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.13.3
