### ISSUE TITLE
[BUG] Components with implicit interfaces not working

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-iot-explorer#353]
I loaded a DTDL v2 on the Catalog and it passed verification.
But in the Explorer, I cannot click on the components

To make it work, I had to **separate** the interfaces into unique files and reference those when creating components in the main device file:

```json
"contents": [
		{
			"@type": "Component",
			"name": "DeviceInformation_2vm",
			"schema": "dtmi:azure:DeviceManagement:DeviceInformation;1"
		},
		{
			"@type": "Component",
			"name": "Exterior_62i",
			"schema": "dtmi:MeshTxs:blereader;1"
		},
		{
			"@type": "Component",
			"name": "Peripherals_62i",
			"schema": "dtmi:MeshTxs:per;1"
		}
	]
```

**Comment by YingXue** [comment]
Hi @uriel-kluk 
Thank you for reporting the issue. It is currently limitation of our dtdl resolve logic. When user click on a component name, the tools goes to local file to fetch corresponding json files. The first file that has the @id matching the schema value would be returned.
Please use the separation as you mentioned above as a workaround, and we will create a task to address this issue.

**Comment by YingXue** [comment]
Fix is released in latest release https://github.com/Azure/azure-iot-explorer/releases/tag/v0.11.4. Closing.
