### ISSUE TITLE
Possibility to communicate with IoT Hub using MQTT over Websockets

### ISSUE THREAD

**Issue by oliverchristen** [Azure/azure-iot-explorer#359]
Often only outbound port 443 is allowed. In this case IoT Explorer does not work assuming it communicates over MQTT port.

As a fallback it should communicate with MQTT over Websockets if this is possible so it would be possible even if only port 443 is available.

**Comment by YingXue** [comment]
Hi @oliverchristen 
Our Explorer tool is a tool to visualize IoT hub like hub status, device's status in the cloud, monitoring device telemetry etc. It not a tool to help connect a real device to the hub. Not sure if the following article is what you are referring to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support? For that, you may want to find a device tool instead.

**Comment by oliverchristen** [comment]
What you explained is absolutely clear to me. The problem I experience in a development environment. The outbound port 1883 is blocked in the company network. If the explorer would communicate using port 443 as a fallback instead, it would work. But today the tool is not usable in these environments.

**Comment by YingXue** [comment]
This request is similar to #372

**Comment by clane2812** [comment]
We face the similar problem - in our company-network the iot-explorer rans into the following error cause of our web-proxy:

Failed to retrieve device list: request to https://xxxxxxxxxxx/devices%2Fquery?api-version=2020-09-30 failed, reason: self signed certificate in certificate chain.

taking a look at wireshark in the meantime port 443 is used by the tool - would it be possible to add the acceptance of self-signed -certificates to the tool?

Out of the company-network everything works fine
