### ISSUE TITLE
[BUG] Azure IoT Explorer v0.12.0 is not able to retrieve the device list

### ISSUE THREAD

**Issue by clm6rt** [Azure/azure-iot-explorer#363]
**Describe the bug**
I am using Azure IoT Explorer v0.12.0 and it is not able to retrieve the device list from IoT Hub. Even though I can see that the device is getting registered with IoT Hub, the Azure IoT Explorer is unable to showcase the same device. It is providing the error “ Failed to retrieve device list: Cannot read property ‘headers’ undefined”. I am using the ‘iothubowner’ shared key for connecting to IoT Hub in the Azure IoT Explorer. Please let me know what should be done to overcome this issue ? 

**To Reproduce**
1. Provide the shared key
2. Connect the Device to IoT Hub 
3. refresh the Device List 
4. No Device will be shown 

**Expected behavior**
The Device List is updated

**Screenshots**
![Iotdevicelist](https://user-images.githubusercontent.com/17411078/95204065-de17bb80-07e3-11eb-8dcc-33cabccdad8d.png)

**Desktop (please complete the following information):**
 - OS: Windows,

**Additional context**

**Comment by clm6rt** [comment]
Sorry Microsoft Team, 

We found the issue, the port 443 was closed on our business Laptops.  
You can consider this issue as solved. 

Best regards,
Martin Clement

**Comment by montgomp** [comment]
Thank you for the follow up, Martin. I'll close the issue.

--Paul

**Comment by logg-sar** [comment]
Hi there

same here, but with Release 0.13.0
Port 443 isnt blocked (I am able to open https://github.com/Azure/azure-iot-explorer/releases/tag/v0.13.0) - but this opens in the installed Browser.

On a Laptop connected directly to the Internet its working with the same Connection String.

This means the software is ok, but not the connection.

Is it possible that IoT Explorer doesnt recognise the proxy configuration of the network?
Where I can see the proxy connection? Where can I adjust it?

**Comment by clm6rt** [comment]
Hello , 

I still face the same issue, I also get an  500 (Internal Server Error) like  @logg-sar. Have you found a solution?
I also was not able to find proxy settings. I was thinking it is blocked by our proxy... 

Best regards,
Martin

**Comment by clm6rt** [comment]
@montgomp  could you please reopen it? It seams it is not only me how has this issue.

**Comment by YingXue** [comment]
Hi @clm6rt 
Please refer to our wiki faq and see if it helps: https://github.com/Azure/azure-iot-explorer/wiki/FAQ#how-to-solve-port-is-in-use

**Comment by YingXue** [comment]
I will close the issue for now. Please reopen if needed anytime.
