### ISSUE TITLE
[BUG] Iot exploer crash with bad type in PnP property and command

### ISSUE THREAD

**Issue by ericmitt** [Azure/azure-iot-explorer#366]
I try to use array in device twin, but used a wrong syntax:

I used in my model:
{
        "@type": "Command",
        "name": "FollowPath",
        "description": "Point to each coordinate in the array passed as parameter and take a picture at each coordinate",
        "request": {
          "path":"[dtmi:com:example:Telescope:CelestialCoordinate;1]"
        }
      },
      {
        "@type": "Property",
        "name": "PathToFollowProperty",
        "schema": ["double"],
        "writable": true
      },
Both are badly handled by iot explorer, see below the screen after trying to look at the writable property tab, or the command tab:
 
![image](https://user-images.githubusercontent.com/6181789/97216586-4f171700-1783-11eb-88a4-ed9d111f7483.png)

**Comment by YingXue** [comment]
Fix has been released, please check it out: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.13.1
Thank you for reporting the issue.
