### ISSUE TITLE
[Feature request] Allow ':' separated certificate fingerprints for self-signed certificates

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-explorer#367]
**Is your feature request related to a problem? Please describe.**
When creating a new X509 device, the format produced by OpenSSL is not accepted:
![image](https://user-images.githubusercontent.com/8635911/98179952-ca2faa00-1eb4-11eb-82b5-c1c181f9c8f1.png)

The format is produced by using
`openssl x509 -text -noout -fingerprint -in mycertificate.pem`

Output:
```
[...]
SHA1 Fingerprint=A0:F7:88:0B:5C:5A:00:BF:55:71:B8:2F:95:47:7B:AA:94:C1:E5:2B
```

**Describe the solution you'd like**
1. Azure IoT Explorer could automatically remove the ":" characters after copy/paste.
2. Allow browsing and opening the Binary DER / Base64 / PEM certificate file. Automatically extract the fingerprint.

This works:
![image](https://user-images.githubusercontent.com/8635911/98180337-7e313500-1eb5-11eb-9382-6305e0fec18e.png)

**Describe alternatives you've considered**
I manually remove the ":" (or using various scripts). 

**Additional context**
It's fairly common to use OpenSSL to generate development certificates for non-automated testing and exploration tasks. This would save a few seconds for every certificate uploaded.

**Comment by YingXue** [comment]
@CIPop 
This ':' enforcement comes directly from the service, so there is not much we can do here. I tried to create the device with the thumbprint you provided directly, and got a badrequest response. If you find it works elsewhere, please let us know and we can follow up from there.

**Comment by CIPop** [comment]
@YingXue I know the server only accepts the format without columns. This is why I've asked for a feature within the UI to be more permissive and automatically produce the correct format.

A good example is the URI. The RFC specifies that www.google.com is an invalid URI (https:// mandatory for any normal form of the URI). That doesn't mean that browsers shouldn't try their best to transform whatever the user inputs (by making assumptions) into something usable (and they get it right 99% of the time for me at least). Same applies here: OpenSSL will output the hash in a `:` separated format. (A lot of other examples: date/time, credit cards, serial numbers for product activation, etc).

My specific request is in pseudocode: `if (hash.Contains(':') hash.Remove(':')`. This should happen automatically and be reflected in the text-box.

**Comment by YingXue** [comment]
@CIPop I see. this is a good idea. let me reopen the issue.

**Comment by YingXue** [comment]
Feature released, please check it out: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.13.1

**Comment by CIPop** [comment]
Awesome! Thank you! This will save me and others using OpenSSL lots of time!
