### ISSUE TITLE
[Feature request] need raw message viewer

### ISSUE THREAD

**Issue by dvescovi1** [Azure/azure-iot-explorer#369]
**Is your feature request related to a problem? Please describe.**
There is no raw message viewer like the old Device Explorer use to have

**Describe the solution you'd like**
An option to turn on and view raw messages

**Describe alternatives you've considered**
Hunting for and loading the old "Device Explorer"

**Additional context**

**Comment by YingXue** [comment]
Hi @dvescovi1 
Can you help provide a screenshot of what you are asking for, and let us know how is it different from the Telemetry tab this tool proivded (with the 'show system properties' checked)?

**Comment by YingXue** [comment]
I will close the issue for now. Please reopen if needed anytime.
