### ISSUE TITLE
Won't run on MacOS

### ISSUE THREAD

**Issue by pelikhan** [Azure/azure-iot-explorer#370]
Installed explorer won't run on MacOS Catalina 10.15.7.

![image](https://user-images.githubusercontent.com/4175913/100149949-304d9280-2e9f-11eb-928f-a19c8b26d591.png)

**Comment by YingXue** [comment]
Hi @pelikhan 
Have you use what's suggested by Apple and see it it works for you: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac
We don't publish this app through App store, so user would run into this issue, but for earlier versions, Mac is not showing this strict of a mesage, but would inform user if they want to trust the app, they can still do so.
