### ISSUE TITLE
[Feature request] Running Inside container

### ISSUE THREAD

**Issue by Haxiboy** [Azure/azure-iot-explorer#371]
Hello!

Is it possible to run it inside docker container and expose port 3000?
I've changed the run command to listen on all hosts and configured dev server to disable host check.
I can reach the web service inside the container from host, but as i can see the running instance inside the container cant connect to azure services, "fetch failed"

Thanks!
Peter

**Comment by YingXue** [comment]
Hi @Haxiboy,
Thank you for reporting the issue.
Can you help us clarify what do you mean by 'expose port 3000'? From what you describe, you are saying you can see the UI, but UI fails to talk to the controller or backend, with error 'fetch failed' is it?

**Comment by YingXue** [comment]
Close the issue due to lack of information.
