### ISSUE TITLE
[Feature request] Enabling Protobuf Message Decoder

### ISSUE THREAD

**Issue by MZDN** [Azure/azure-iot-explorer#383]
**Problem**
Not all messages sent by devices are in json. They can be also be in protobuf, zlib or another format.

**Solution description**
Since protobuf is mostly used as message exchange format, there should be a possibility on the azure iot explorer to choose a decoder (for protobuf) in order to see/verify the messages that are being read from iot-hub. If the user chooses the decoder protobuf, he should able to upload the protobuf description of the expected messages. The user can then see the messages in for human readable format.

**Comment by YingXue** [comment]
Hi @MZDN 
Thank you for reporting this issue. We will look into this.

**Comment by MZDN** [comment]
That will be awesome! Thanks @YingXue!

**Comment by YingXue** [comment]
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.1 has addressed the issue.
We've provided a command with a a panel on Telemetry page for user who would like to use protobuf.

**Comment by JedidiahPaterson** [comment]
I know this is close but along these lines could there also be a CBOR decoder?
