### ISSUE TITLE
[BUG] Errors when connection to IoTHub preview (GW v2)

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#384]
Create a Hub in preview mode https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-preview-mode#using-an-iot-hub-in-preview-mode

When trying to connect from IoTExplorer (0.13.3.0)  I got the error below.

```
Failed to retrieve device list: Cannot read property 'headers' of undefined
```

**Comment by YingXue** [comment]
Hi @rido-min 
I am not able to repro this issue myself with a preview hub. I suspect the error is caused by something else. To verify, you may want to create another hub with preview and see if this message consistently appear.

**Comment by rido-min** [comment]
I created a new preview hub and I'm not seeing this error.
