### ISSUE TITLE
[BUG] The UI fails to properly display a users Enum selection. It's removed/blanked out.

### ISSUE THREAD

**Issue by SillyKeith** [Azure/azure-iot-explorer#385]
**Describe the bug**
This is a Visual UI bug and can cause user confusion.

When using the UI to select the first Enum value via the Dropdown, it will always blankout the selected text if your previous selection was Enum 2, 3, etc.   The actual value however is processed correctly when pushing "Update desired value" to a device.

**To Reproduce**
1. Setup a device PnP connection and load the dtmi:osconfig:deviceosconfiguration;1
2. In IoT Plug and Play Components section, click the "Settings" component.
3. When the interface comes up, select "Properties (writable)
4. From the "DeviceHealthTelemetryConfiguration" , select *None*.
5. (sometimes the visual bug is hit and the text "None" disappears.)
6. Change your selection from the drop down to *Required*.
7. Change your selection from the drop down back to *None*.   **Issue is hit and the text is always blanked out.**

**Note: not all dropdowns or enum selections exhibit this behavior, but this one consistently repros the issue.**

**Expected behavior**
The text from a users dropdown selection should always be displayed.

**Screenshots**

https://user-images.githubusercontent.com/28606059/105085225-4d8c8080-5a4c-11eb-81c2-d8987d42b56e.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version:  20H2 (19042.746)
 - App version: 0.13.3.0

**Additional context**

**Comment by YingXue** [comment]
Hi @SillyKeith  
Thank you for reporting the bug. Can you help provide the dtdl schema of that enum that you are consistly hitting the issue with? This would be quite helpful for us to debug. Thank you.

**Comment by SillyKeith** [comment]
Here it is: iot-plugandplay-models-test/dtmi/osconfig at 7211a4271c97a0e6e664d676ce840ceda2d202ee * Azure/iot-plugandplay-models-test (github.com)<https://github.com/Azure/iot-plugandplay-models-test/tree/7211a4271c97a0e6e664d676ce840ceda2d202ee/dtmi/osconfig>
It's in the settings-1.json

Keith Kepler
[See the source image]
Keith Kepler
Azure Edge + Platform | Sr. Program Manager
[cid:image002.png@01D6EE6B.E5FF1820] Chat with me via Teams!<https://teams.microsoft.com/l/chat/0/0?users=keith.kepler@microsoft.com> | keith.kepler@microsoft.com<mailto:keith.kepler@microsoft.com>

**Comment by YingXue** [comment]
The fix has been deployed in our latest version 0.13.4.
Closing.
