### ISSUE TITLE
[BUG] Support the expanded format used in Central and DeviceModelRepo

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#388]
Export a PnP model from Central
Configure IoTExplorer to `resolve` PnP interfaces from the folder where the model was saved

Expected. IoTExplorer can use the model
Observed. 

```
dtmi:feiht:kraftwerk;1 cannot be retrieved from local folder. Here is a list of json files with errors that we encountered 
while parsing: Kraftwerk_central.json: Cannot read property 'toString' of undefined, model_index.json: Cannot read 
property 'toString' of undefined. Please note that trailing comma is not allowed in json files.
```

This happens because Central exports using the [expanded format](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Resolution-Convention#expanded-dependencies). 

Should be fixed by using the dmr-client libraries for node https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/node

Nit. Can we improve the error message?

found by @wickste

**Comment by YingXue** [comment]
Hi @rido-min 
Thank you for reporting the issue. We will look into this.
It would be great if you can also attach the models that you are using for us to verify if our changes would be working.

**Comment by rido-min** [comment]
Central uses the [expanded format](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Resolution-Convention#expanded-dependencies). 

You can find examples by adding `.expanded.json` to any interface in the DMR eg. https://devicemodels.azure.com/dtmi/advantech/epc_u2117-2.expanded.json

**Comment by YingXue** [comment]
Release 0.13.5 is out to address this issue: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.13.5
Closing.
