### ISSUE TITLE
[Feature request] Enable Edge Device Creation

### ISSUE THREAD

**Issue by nainesh72** [Azure/azure-iot-explorer#398]
How  I creaet IOT edge Device using this explore 
we create Device not EdgeDevice How we Do

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YingXue** [comment]
Hi @nainesh72  thank you for creating this issue. This is currently on our backlog, and will have an update for it once we plan it out.

**Comment by YingXue** [comment]
Closing this issue and will be tracking in #404
