### ISSUE TITLE
Port 8081 is in use by another application. Hence, cannot install Azure IoT Explorer

### ISSUE THREAD

**Issue by manishakumari1992** [Azure/azure-iot-explorer#427]
I tried to install Azure IoT Explorer on my local machine. But got the message that Port 8081 is already in use by another application. In this case McAfee Security.

This wiki talks about overruling the port yet this doesn’t appear to work for us (confirmed on multiple win 10 systems)
https://github.com/Azure/azure-iot-explorer/wiki/FAQ

Azure IoT Explorer is the overriding variable and the same issue arises

**Comment by montgomp** [comment]
Recent release removed the code that checks for environment variable for port number. PR #434 addresses this.
