### ISSUE TITLE
[BUG] Chocolatey install fails with hash mismatch

### ISSUE THREAD

**Issue by juunas11** [Azure/azure-iot-explorer#428]
**Describe the bug**

When installing the IoT Explorer from Chocolatey with the command:

```
choco install azure-iot-explorer --pre
```

The following errors are logged:

> Error - hashes do not match. Actual value was 'BF8DF6BC98A3E6F8262DC435779B44E6840C568ADAB8949004546449F2400D1E'.
> ERROR: Checksum for 'C:\Users\User\AppData\Local\Temp\chocolatey\azure-iot-explorer\0.13.0-preview\Azure.IoT.Explorer.preview.0.13.0.msi' did not meet 'CD4050AC2C5040D0802B2CED27A5BDF6B1D9C2F23C223D8FF4AA4284CF353A06' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of azure-iot-explorer was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\azure-iot-explorer\tools\chocolateyinstall.ps1'.

**To Reproduce**
1. Try to install with Chocolatey

**Expected behavior**
The application is installed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 20H2 (Build 19042.867)
 - App version: 0.13.0-preview

**Additional context**
- Chocolatey version: 0.10.15

**Comment by montgomp** [comment]
I am working on the chocolatey package and expect to have `0.14.1-preview` available soon.

**Comment by montgomp** [comment]
@juunas11 running `choco install azure-iot-explorer --pre` should work as expected and install version 0.14.1

Let me know if this is not the case and we can reopen this issue.

Thanks
