### ISSUE TITLE
[BUG] App does NOT retain last screen hight and width settings after quit

### ISSUE THREAD

**Issue by anthonyvercolano** [Azure/azure-iot-explorer#432]
**Describe the bug**
App does NOT retain last screen hight and width settings.

**To Reproduce**
Start app.
Grab a corner and give it a different height and width.
Quit App.
Start App.
Height and width seem to default to a set size NOT what had been set before the quit.

**Expected behavior**
Expect it to be as it was when I quit.

**Desktop (please complete the following information):**
 - OS: OSX
 - OS 11.2.3
 - Azure IoT Explorer Version 0.14.1 (0.14.1.20210323.1)

**Comment by montgomp** [comment]
PR #434 leverages NPM package `electron-window-state` to track window state to apply previous window state on launch.
