### ISSUE TITLE
Content Type system property not appearing for Telemetry.

### ISSUE THREAD

**Issue by momuno** [Azure/azure-iot-explorer#444]
**Describe the bug**
When observing telemetry from the device, and having selected "Show system properties", the content type system property does not appear even though it is appended to the topic.

**To Reproduce**
For the device application, set the content type system property for sending telemetry, so the topic appears as: 
`devices/{device_id}/messages/events/%24.ct={url-encoded-content-type}`
Run the device application to begin sending telemetry.

In Azure IoT Explorer, for the device:
1. Go to 'Telemetry`
2. Click on 'Show system properties'
3. Click on 'Start'
4. Receive telemetry.
5. View system properties reported as part of the telemetry:

```
    "systemProperties": {
        "iothub-connection-device-id": "xxx",
        "iothub-connection-auth-method": "xxx",
        "iothub-connection-auth-generation-id": "xxx",
        "iothub-enqueuedtime": xxx,
        "iothub-message-source": "Telemetry",
        "x-opt-sequence-number": xxx,
        "x-opt-offset": "xxx",
        "x-opt-enqueued-time": xxx
      }
```

**Expected behavior**
The content-type system property should be listed, but it is not.

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - App version: Azure IoT Explorer (preview) 0.14.3.0

**Additional context**
Sending C2D messages with the content type system property does work, and the topic appears as:
`devices/{device_id}/messages/devicebound/%24.mid={mid_value}&%24.to=%2Fdevices%2{device_id}%2Fmessages%2Fdevicebound&%24.ct={url-encoded-content-type}`

**Comment by YingXue** [comment]
Hi @momuno 
This tool is not stripping any system properties out itself, but rather shows what it can see from event hub.
Have you try to verify if you can see this specific system property using other tools, for example Azure CLI?

**Comment by YingXue** [comment]
Closing as no additional info has been provided.

**Comment by momuno** [comment]
Hi @YingXue.  Looks like I missed your earlier comment.  Thanks for you reply, and I will take a look.
