### ISSUE TITLE
[Feature request] Access Iot Hub data with the appropriate RBAC role instead of the Connection String

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-iot-explorer#446]
**Is your feature request related to a problem? Please describe.**
I cannot explore an IoT Hub (devices, twin, queries ...) without having the secret connection string of the IoT Hub. For security reasons this connection string is not something always available.

**Describe the solution you'd like**
I would like to be able to login to Iot hub Explorer with my azure account (supposing that my account already has the appropriate role) and access the IoT hubs my account has permission to explore without having to provide a connection string. This is what I am used to do with the azure storage explorer which is quite similar to the iot hub explorer tool.

**Describe alternatives you've considered**
I considrered using vs code extension for iot hub, but there is the same issue.

**Comment by rido-min** [comment]
@TechWatching Thanks for the feedback, this feature is actually in our backlog and will be implemented soon.

**Comment by YingXue** [comment]
Authentication through AAD has been released in this version: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.0
Please check it out.
Note that if you've disabled local auth, the app is not expected work. This is a task still on the backlog.

**Comment by TechWatching** [comment]
@YingXue I have noticed a few problems : 

- when logged in, log out does not really log out (impossible to sign in with another user, it automatically log in with the previous user connected)
- impossible to connect with personal accounts (my personal account has a subscription I would like to use)
- not all tenants / subscriptions are displayed

I succeeded to connect to an iot hub with a test account I created on my tenant but I think the problems I mentioned above should be corrected.

**Comment by rtheil-growlink** [comment]
I just installed latest, and when I log in I get no subscriptions even though I have access to multiple IoT hubs. Is there a specific permission one needs to have for this to work? I plan on having someone with more permissions try this out to see if it works.

I agree with @TechWatching that it's not possible to change login info.
