### ISSUE TITLE
[BUG] Nav flaky when in PnP component details

### ISSUE THREAD

**Issue by montgomp** [Azure/azure-iot-explorer#450]
**Describe the bug**
The 'Device identity' nav item is not clickable within the context of a PnP component.

**To Reproduce**
1. Go to any PnP device
1. Click on 'IoT Plug and Play components'
1. Click on any component in grid.
1. Click on 'Device identity' (it does not fire event).
1. Click on any other nav item (Device twin, Telemetry, etc). They work.
1. Click on 'Device identity'. It now works.

**Expected behavior**
The 'Device identity' nav item should fire the navigation regardless of the content in the right panel.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - App version 0.14.4

**Comment by YingXue** [comment]
Fixed in release 0.14.7
