### ISSUE TITLE
[BUG] Crash (blank screen) when using contents without Array

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#451]
DTDL allows to define `contents` as array or an object.

When using object, IoTExplorer crashes and shows a blank screen.

Example model:

```json
{
  "@context": "dtmi:dtdl:context;2",
  "@id": "dtmi:test:contentsWithObject;1",
  "@type": "Interface",
  "contents": {
    "@type": "Property",
    "name": "myProp",
    "schema": "string"
  }
}
```

Note the .NET parser allows this syntax

**Comment by YingXue** [comment]
release 0.14.5 is now out with fix. closing.
