### ISSUE TITLE
[BUG] when Azure IOT Hub have big amount device, azure-iot-explorer can not get the device list

### ISSUE THREAD

**Issue by hylinux** [Azure/azure-iot-explorer#453]
**Describe the bug**
customer have a big mount device in their Azure IoT Hub,  and they found they can not use this tool list the device list, but Azure Cli and powershell is ok. 
![image](https://user-images.githubusercontent.com/145199/125726250-7479ce0b-daf4-4929-be94-450aaa882f90.png)

and I tried to use Fildder to capture the network trace, I found azure-iot-explorer tried to access localhost: 
POST http://127.0.0.1:8081/api/DataPlane HTTP/1.1
Host: 127.0.0.1:8081
Connection: keep-alive
Content-Length: 742
Cache-Control: max-age=0
accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) azure-iot-explorer/0.14.4 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
content-type: application/json
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN

{"apiVersion":"2020-06-30-preview","body":"{\"query\":\"\\n    SELECT deviceId as DeviceId,\\n    status as Status,\\n    lastActivityTime as LastActivityTime,\\n    statusUpdatedTime as StatusUpdatedTime,\\n    authenticationType as AuthenticationType,\\n    cloudToDeviceMessageCount as CloudToDeviceMessageCount,\\n    connectionState as ConnectionState,\\n    capabilities.iotEdge as IotEdge,\\n    modelId as ModelId\\n    FROM devices \"}","headers":{"x-ms-max-item-count":100},"hostName":"iothub-konnect-prd.azure-devices.cn","httpMethod":"POST","path":"devices/query","sharedAccessSignature":"xxxxxx(I removed it}"}

and the response is:

HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: http://127.0.0.1:3000
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 71
ETag: W/"47-EqBsBSZBGTzp3zjjA8kiA+MHAIo"
Date: Thu, 15 Jul 2021 03:48:33 GMT
Connection: keep-alive

{"body":{"Message":"Failed to get any response from iot hub service."}}

**To Reproduce**
1. input the connect string
2. jump the error 

**Expected behavior**
after connect to iot hub, can show the device list
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 
 - OS Version: windows 10
 - App version: 0.14.4.0

**Comment by YingXue** [comment]
Hi @hylinux 
Thank you for reporting the issue. Can you let us know what's the size of devices that we are looking at here?

**Comment by YingXue** [comment]
Closing as no additional info has been provided.
