### ISSUE TITLE
[BUG] Unable to Monitor Telemetry Events

### ISSUE THREAD

**Issue by ravitol** [Azure/azure-iot-explorer#456]
All

I upgraded to version 0.14.4 and am unable to see the Telemetry events. 

I am able to go to navigate to the IoT Hub and list the devices.  However when I click on the Telemetry, it does not show the CG and allow me to select the $default or the Monitor CG that I have setup.  

See the screen shot below. I also tried to reinstall the latest version and also tried to get add and remove the Azure IoT Hub but this did not work.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/747544/126326423-e31a56ea-3078-44dd-999e-ae34b93c8a8c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version:10.X
 - App version 0.14.2

**Additional context**

**Comment by ravitol** [comment]
I was able to downgrade to a prior release 0.14.3 and this worked 👍.   Hence it may be something with this release

**Comment by yahanda** [comment]
+1. I had the same issue in 0.14.4 and it worked fine after downgrading to 0.14.3.

**Comment by YingXue** [comment]
Hi, we spotted a bug in our updated library, and the code fix is in but not yet merged. You can try to make the app screen narrower or wider, then the content would be showing up again. Sorry for the inconvinience, and we will release a new version to get the fix out soon.

**Comment by YingXue** [comment]
release 0.14.5 is now out with fix. closing.
