### ISSUE TITLE
[BUG] Cannot monitor F1 tier IoT Hub device telemetry data

### ISSUE THREAD

**Issue by renakim** [Azure/azure-iot-explorer#481]
**Describe the bug**
F1 tier IoT Hub device telemetry is not monitored (S1 tier is work)
I checked issue #218 and removed the old F1 tier hub and created a new one, but the problem is the same.

But, I can monitor with az cli for same hub/device. (az iot hub monitor-events -n <hubname>)
I tested with MQTT Client tool (MQTT.fx) and Azure IoT Samples for Node.js.

While checking for differences F1 and S1, I found that the Event Hub-compatible name was different.
The Event Hub-compatible name of S1 is same with IoT hub name, but F1 is not. (iothub-ehub-<hubname>-<some ids>...)

Could this be related?
Or if there is another cause, please check.

**Screenshots**
- Azure IoT Explorer
![image](https://user-images.githubusercontent.com/29771876/142133560-a277ae7f-344f-4134-b6a8-87563581c27f.png)

- az cli
![image](https://user-images.githubusercontent.com/29771876/142132526-01174936-a173-4381-a30d-0b4a064dcc42.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Azure IoT Explorer version: 0.14.7.0

**Comment by themegaphoenix** [comment]
Hi,
Please try version 0.14.5
#477

**Comment by renakim** [comment]
Hi @themegaphoenix,
I tried version 0.14.5, it works. Thanks.
But it still doesn't work in version 0.14.7. needs check.

**Comment by YingXue** [comment]
Please check if the issue still happens in https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.8
We are not able repro the issue on our side.

**Comment by YingXue** [comment]
Release 0.4.10 should have this issue addressed.

**Comment by renakim** [comment]
Hi, I tested the function (monitor telemetry on F1 tier IoT Hub device) with Release 0.14.10, and the issue doesn't happen.
Thank you.
