### ISSUE TITLE
[BUG] v0.14.7.0 Windows cannot retrieve the telemetry from IoT Hub

### ISSUE THREAD

**Issue by timzhan** [Azure/azure-iot-explorer#486]
**Describe the bug**
Azure IoT Explorer 0.14.7.0 Windows edition cannot retrieve the telemetry from IoT Hub.

**To Reproduce**
1. Go to 'Home > IoT Hub > Devices > DeviceId > Telemetry'
2. Click on 'Start'
3. It shows  'Receiving events ....', but no data is showing up and just hangs there.
4. It seems this issue doesn't exist on Windows edition 0.14.5.0.

**Comment by rido-min** [comment]
can you verify your routing settings in hub are correct by trying to watch telemetry from the CLI ? `az iot hub monitor-events`

**Comment by YingXue** [comment]
Please check if the issue still happens in https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.8
We are not able repro the issue on our side.
