### ISSUE TITLE
[Feature request] Automatically point to devicemodels.azure.com model repository

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-explorer#490]
While bringing up a PnP model that was in the published model repository, I was surprised at 1st that it didn't just resolve.  I'd setup the local folder for models, but didn't realize I had to explicitly opt-in via the "IoT Plug and Play Settings"=>Add and then chosing public-repository.

Could we make this so that we just default to using it as I'd think a large % of time that'd be right thing.  I haven't looked in a bit but I'm almost positive that's what IoT Central does as well??

**Comment by YingXue** [comment]
We are looking into this issue.

**Comment by shahm5** [comment]
This had been added and will be in the next release
