### ISSUE TITLE
[Feature request] Add result from direct method call

### ISSUE THREAD

**Issue by rtheil-growlink** [Azure/azure-iot-explorer#495]
Doing firmware development for devices using Azure IoT. Working on implementing direct method calls. I prefer IoT Explorer because the Direct method screen doesn't delete the method name or payload after invoking. This means I can send the same command over and over again until the firmware does what I want. Azure portal wipes these fields on every invoke. What's missing is the result from a direct method call, as seen here:
![image](https://user-images.githubusercontent.com/96268167/157549894-7d1a0b4c-0107-4bde-a378-a3d67b9a6e51.png)

I'd like to see the result from the direct method call in its own readonly text box below the "Response timeout in seconds" slider, like it is in the Azure web portal.
![image](https://user-images.githubusercontent.com/96268167/157549784-1d3c2ef5-5956-4624-a54b-b79faf3bcc5c.png)

Right now the problem is that the result only shows in a pop up notification in the corner then disappears. Can't copy or examine the response body, especially when large. Often I take that response and drop it in jsonlint.com to look at the data.
![image](https://user-images.githubusercontent.com/96268167/157550517-8bbf52ee-d5e0-4c75-98df-457ddeb2320f.png)

**Comment by YingXue** [comment]
Hi @rtheil-growlink
We did tackle issue a while back, and the decision we made is giving users a 'Notification Center'.
If you go back to home, you should be able to locate it - the third item in left nav.
We didn't provide a link in short messages, but if your response is super long, we will show a cropped message and inform you that the full message is in the 'Notification Center' to make it more accessible.

**Comment by rtheil-growlink** [comment]
Thanks for that info. Here's why that doesn't work well:

I choose an iot hub, go to devices, search for a device, click that device, click direct method, enter my direct method details, and click invoke. I then get a notification, it disappears, I need to copy the text from the response. So I click home, click notification center, choose the notification, then copy my text. Now I need to call that direct method again. So I choose an iot hub, go to devices, search for a device, click that device, click direct method, enter my direct method details, and click invoke.

The problem here is the constant repeating of the process to get to the direct method, or other, screen in order to get the notification I need to copy the response from. Having to go to notifications is time consuming.

**Comment by rtheil-growlink** [comment]
This one really shouldn't be closed, as the "workaround" isn't really helpful at all, and is far too time consuming to be useful for development purposes.

**Comment by YingXue** [comment]
Relates to #514

**Comment by YingXue** [comment]
> Thanks for that info. Here's why that doesn't work well:
> 
> I choose an iot hub, go to devices, search for a device, click that device, click direct method, enter my direct method details, and click invoke. I then get a notification, it disappears, I need to copy the text from the response. So I click home, click notification center, choose the notification, then copy my text. Now I need to call that direct method again. So I choose an iot hub, go to devices, search for a device, click that device, click direct method, enter my direct method details, and click invoke.
> 
> The problem here is the constant repeating of the process to get to the direct method, or other, screen in order to get the notification I need to copy the response from. Having to go to notifications is time consuming.

Oh I forgot to point out one thing that could make your life easier before the next release (which is btw coming early next week where we added a copy button next to the response), there is a 'go back' button on top of the notification center's page, which directly take you back to where you came from, and in your case the 'direct method' page.

**Comment by rtheil** [comment]
Oh, interesting. I have never noticed that. Not sure, based on its position, if I would have realized it's to go back to where I was. Will watch for that in my next tests.

**Comment by rtheil-growlink** [comment]
Oh, interesting. I have never noticed that. Not sure, based on its position, if I would have realized it's to go back to where I was. Will watch for that in my next tests.

**Comment by YingXue** [comment]
Releasing https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.11 which adds copy button on both places and fix scroll bar to the notificaiton center.
