### ISSUE TITLE
Telemetry not displaying message correctly

### ISSUE THREAD

**Issue by bhnaphade** [Azure/azure-iot-explorer#498]
The telemetry data displays messages in ascii associated decimal numbers instead of Characters that were sent.
<img width="590" alt="image" src="https://user-images.githubusercontent.com/15098992/160620101-b5ee8ff6-48da-41ec-8f10-a8733e2278b8.png">

This message should display "Hello" but is shows up as decimal values for each character.

I had  v013.5 previously , which showed messages in characters.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/15098992/160627511-89d237ff-7b70-42ca-a0a6-909c1b7a3a19.png">

**Comment by rido-min** [comment]
May I ask you which SDK or library are you using to send telemetry?

**Comment by bhnaphade** [comment]
This is without SDK, my setup includes Cellular modem connected to COM port terminal on PC  and I am sending AT commands to publish message

**Comment by Sandlerdev** [comment]
I am seeing this as well.  The SDK in use is the JavaScript library.

**Comment by YingXue** [comment]
Hi, 
After version 0.14.7, we have updated the Event Hub's SDK for telemetry monitoring, where their older SDK has been depcreated.
The message body type in their SDK is now an 'any' type.
![image](https://user-images.githubusercontent.com/5489222/179849008-0d2265b3-2ce4-4841-88e8-bd3543e1de08.png)

Explorer will be showing the body as is without any conversion as a dev tool to reveal what's truly under the cover. If you are sending the string properly, we will be able to show it properly as well. 
For example, I am sending az iot device simulate --device-id test1 --login "<my hub connections string>" --data "n\HELLO", and I am able to see the following properly from explorer:
![image](https://user-images.githubusercontent.com/5489222/179849285-5dff4f08-b3be-46f8-b752-cc5f13cc75e9.png)

**Comment by YingXue** [comment]
We will release 0.14.10 soon to revert this sdk change.

**Comment by timscchao** [comment]
Tested on 0.15.0, still get decimal numbers output when publish string.

az iot device send-d2c-message -n igstesthub -d igstestdevice --data "\nHELLO"

{
  "body": {
    "0": 92,
    "1": 110,
    "2": 72,
    "3": 69,
    "4": 76,
    "5": 76,
    "6": 79
  },
  "enqueuedTime": "Mon Oct 24 2022 14:09:37 GMT+0800 (台北標準時間)"
}

Test env:
az version
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.15.0"
  }
}
