### ISSUE TITLE
support direct method calls to IoT Edge modules

### ISSUE THREAD

**Issue by dvescovi1** [Azure/azure-iot-explorer#500]
**Is your feature request related to a problem? Please describe.**
Can not send direct method requests to IoT Edge modules

**Describe the solution you'd like**
Support direct method requests to edge modules just like to devices

**Describe alternatives you've considered**

**Additional context**

**Comment by YingXue** [comment]
Hi there. We won't be able to support Edge in a while due the bandwidth. Will keep it in our backlog.
