### ISSUE TITLE
[BUG]Mac OS prebuilt binary not notarized during the package process

### ISSUE THREAD

**Issue by vitoriammg** [Azure/azure-iot-explorer#503]
**Describe the bug**
Mac OSX doesn't authorize application to install. 
**To Reproduce**
1. Go to  https://github.com/Azure/azure-iot-explorer/releases and download the file Azure.IoT.Explorer.preview.-0.14.5.dmg
2. See a system error "“Azure IoT Explorer (preview)” cannot be opened because Apple could not check for malicious software."

**Desktop :**
- OS: OSX
-OS Version:10.15 Catalina M1 x64
-App version: 0.14.5

**Comment by YingXue** [comment]
Hi, the fact that you see this error message is because we are not releasing this app through apple store.
Please find relevant articles from Apple and proceee with 'open/trust the app anyway' to unblock yourself.
This tool is still in preview. We will address this issue before it's GA.
