### ISSUE TITLE
[BUG] IoT PnP: Empty string not allowed in "mapValue": { "name": "xyz", "schema": "string"}

### ISSUE THREAD

**Issue by Salazander** [Azure/azure-iot-explorer#505]
**Describe the bug**
I'm working on the DTDL definition of a new OSConfig module. 
Here's the work in progress: https://github.com/Salazander/iot-plugandplay-models/blob/main/dtmi/osconfig/pmc-1.json
I tried to set a "mapValue" of type "string" to "" (empty string) using Azure IoT Explorer, but the input validation rejects empty strings.
![image](https://user-images.githubusercontent.com/29793164/165237477-9a231a3f-bb9d-4007-a73e-f044484cf09c.png)

Since setting an empty string is overloaded with a very specific meaning in our case, setting "" as mapValue is valid from our point of view. Is there anything in the docs that suggest that empty strings are invalid? https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#map

**To Reproduce**
1. Add a writeable Property with a map to any PnP Model that gets loaded from a local folder
```
{
  "@context": "dtmi:dtdl:context;2",
  "@id": "dtmi:osconfig:pmc;1",
  "@type": "Interface",
  "displayName": "Repro",
  "description": "Repro",
  "contents": [
    {
      "@type": "Property",
      "name": "desiredState",
      "schema": {
        "@type": "Object",
        "fields": [
          {
            "name": "sources",
            "schema": {
              "@type": "Map",
              "mapKey": {
                "name": "id",
                "schema": "string"
              },
              "mapValue": {
                "name": "entry",
                "schema": "string"
              }
            }
          }
        ]
      },
      "writable": true
    }
  ]
}
```

3. Open Device -> Module identities > IoT Plug and Play components -> Properties (writable) 
4. Try to set an empty string as input parameter for entry
5. -> Input validation fails

**Expected behavior**
An empty string "" is a valid input parameter for mapValues of type "string"

**Screenshots**
![image](https://user-images.githubusercontent.com/29793164/165245491-4018d3b3-66f7-4d90-953d-85c586f130e2.png)
Note the unrelated validation issue with numbers.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 22000.613
 - App version: local build based on latest main and Preview Release 0.14.5.0

**Comment by YingXue** [comment]
Hi @Salazander 
The asterisk start beside 'entry' does indicate this is a required property.
At the time everything is a required a property, so that's what this tool is enforcing.
I remember there has been discussions around DTDL languages support optional property before, unfortunately we are lacking bandwidth to update the tool to keep up the latest. 
Will keep this item in our backlog, and when the time comes we will update the tool to be compliant with DTDL v3

**Comment by YingXue** [comment]
Fixed released in https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.8. Closing.
