### ISSUE TITLE
[BUG] "Error in controller process" message box popup and shows "Unhandled error" while start telemetry monitor

### ISSUE THREAD

**Issue by wisedgelink** [Azure/azure-iot-explorer#526]
**Describe the bug**

"Error in controller process" message box popup and shows "Unhandled error" while start telemetry monitor

**To Reproduce**
1. Open Azure IoT Explorer (version 0.14.11.0)
2. Open an iothub instance in the "IoT hubs" tab
3. Open a device for monitoring
4. Click on Telemetry in left panel, then click start button in right panel
5. Wait few seconds, the message box shows.

**Expected behavior**
no error occur and I can see the event message published by device.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/109322073/182742406-79988fd4-7f2b-4492-b841-2e821674ab61.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Professional 21H2
 - App version: 0.14.11.0

**Comment by YingXue** [comment]
Hi,
Can you let us know if it is consistent or intermittent?

**Comment by wisedgelink** [comment]
> Hi, Can you let us know if it is consistent or intermittent?

It is consistent.

**Comment by YingXue** [comment]
Hi @wisedgelink 
We are able to repro the same issue, but it's under the circumstances that the hub is having intermittent connection issue itself. I am suspecting that the iot hub itself is having trouble connecting to it's underlying event hub as the error is implying. The 'symptoms' of hub having issue includes that this tool intermittent cannot show device list, device identity or other pages correctly.
However, as this tool only interact with devices (through hub's connection string login), it is only aware of what is happening on [DataPlane but not ControlPlane ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/control-plane-and-data-plane). We cannot know what is happening with the IoT hub itself, nor to get any meaning error. 
We would recommend going to azure.portal.com and check if anything seems off. 
Also if you have another hub you can use, please check if this error is happening again when you don't see intermittent connection issue on other pages.

**Comment by YingXue** [comment]
The bug has been closed due to lack of recent actively. Please let us know if this needs to be reopened.
