### ISSUE TITLE
Different Cloud message MQTT topic format devicebound 

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/azure-iot-explorer#530]
when I receive a cloud message from this tool in a device using MQTT only (as explained [here](https://sandervandevelde.wordpress.com/2022/08/12/exploring-full-azure-iot-hub-device-support-using-mqtts-only/)) the response differs from a comparable request in the Azure portal:

```
// Received from IoT Explorer tool
"devices/nonsdkdevice/messages/devicebound/%24.mid=f618dedc-210e-4c68-956d-160577b2ca01&%24.to=%2Fdevices%2Fnonsdkdevice%2Fmessages%2Fdevicebound&key1=value1&key2=value2"

// Received from the Azure portal
"devices/nonsdkdevice/messages/devicebound/%24.to=%2Fdevices%2Fnonsdkdevice%2Fmessages%2FdeviceBound&%24.ct=text%2Fplain%3B%20charset%3DUTF-8&%24.ce=utf-8&bbb=bbbb&aaa=aaaa"
```

- There is this '.mid' instead '.to'
- 'devicebound' instead of 'deviceBound' (there are two in the same topic string)
- No .ct and .ce

**To Reproduce**
1. have MQTT device client running like this C# one: https://github.com/sandervandevelde/NonSDKAzureIoTClient
2. select the device
3. send a cloud message 
4. compare the response with the same message as seen in the azure portal

**Expected behavior**
I expect this MQTT topic to be on par with the Azure portal behavior.

**Additional context**

The github repo of an MQTT client is found here: https://github.com/sandervandevelde/NonSDKAzureIoTClient
A blog explains the full IoT Hub support: https://sandervandevelde.wordpress.com/2022/08/12/exploring-full-azure-iot-hub-device-support-using-mqtts-only/

**Comment by YingXue** [comment]
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.1 has addressed the issue.
The format may still not be exactly the same, but we are surfacing directly from the APIs calls from the service, and will consider this issue as closed.
