### ISSUE TITLE
[BUG] The module twin editor does not scale with the window size

### ISSUE THREAD

**Issue by licensedslacker** [Azure/azure-iot-explorer#531]
**Describe the bug**
Module twin editor does not resize with the window. The editor is fixed to 18 visible lines. However, the device twin editor scales with the window. This has been broken in versions 0.14.11 and 0.14.12. The last working version was 0.14.10.

**To Reproduce**
1. Go to 'Module twin' view
2. JSON editor is fixed to 18 visible lines.

**Expected behavior**
The editor shall scale with the window as the device twin editor does.

**Screenshots**
![module_twin](https://user-images.githubusercontent.com/37897135/184597370-86a393c5-0dc8-4dd2-a4de-4b2bc5bb1afb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10 21H1
 - App version: 0.14.12

**Additional context**

**Comment by shahm5** [comment]
This has been fixed to match the device twin editor and will be there in the next release
