### ISSUE TITLE
[BUG] Error when reading telemetry events

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-iot-explorer#533]
The receiving of telemetry events does not work.

**To Reproduce**
0. Install the latest version of IoT Explorer
1. Select any Device 
2. Start listening

**Expected behavior**
Receiving starts

**Desktop:**
 - OS: Windows 11

![image](https://user-images.githubusercontent.com/1756871/184711749-3404363b-33f3-4d7a-bcae-bc48716f2592.png)

**Comment by YingXue** [comment]
Hi @ddobric do you mind take a look at this issue's response, and let us know if you are experiencing intermittent connection issue with your hub: #526

**Comment by ddobric** [comment]
Thanks for the quick response @YingXue. In the meantime, I have changed my physical location. Having the still same issue.
Btw., I also have devices which send events to the IoT hub. Events are definitely in there.

**Comment by YingXue** [comment]
Hi @ddobric 
We did notice an issue with our event hub SDK dependency and rolled out a [new version](https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.13) with the fix.
Would you mind give it a try and see if it's still happening.

**Comment by YingXue** [comment]
Closing the issue due to no further replies.

**Comment by ddobric** [comment]
Thanks @YingXue . It works now with the new version.
