### ISSUE TITLE
[Feature request] display "properties": { "system": {} } in Telemetry monitoring.

### ISSUE THREAD

**Issue by tahirai-outlook** [Azure/azure-iot-explorer#539]
Telemetry monitoring displays properties
**IoTHubMessage_SetProperty**
https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-setproperty
= *az iot hub monitor-events --properties app*

but doesn't display properties - system like
**IoTHubMessage_SetContentEncodingSystemProperty**
https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-setcontentencodingsystemproperty
**IoTHubMessage_SetContentTypeSystemProperty**
https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-setcontenttypesystemproperty
= *az iot hub monitor-events --properties sys*

"show system properties" check box works like
*az iot hub monitor-events --properties annon*

could you display like below?
*az iot hub monitor-events --properties all*

az command;
![az](https://user-images.githubusercontent.com/44558253/185458510-a46f5ee9-2e1a-4c89-8af4-063163ae336c.png)

iot explorer:
![iotexplorer](https://user-images.githubusercontent.com/44558253/185458551-1291e5ee-7c8c-4639-9082-33c783ff35e5.png)

**Comment by YingXue** [comment]
Hi @tahirai-outlook
I'd like to get some clarification of what the feature request is with you.
Would you like us to add system property (content-encoding and content-type) into properties, and change our rename the system properties section with annotations?
Explorer is using the event hub node sdk where our CLI is not. While analysing their SDK code, we did verified that we are using the terms provided by them, meaning the annotations that you see in CLI is indeed named as system properties, and we are not altering what they are showing to us but directly refect what was provided.
