### ISSUE TITLE
[BUG] Unable to start running telemetry via v0.14.13

### ISSUE THREAD

**Issue by RedDogUK** [Azure/azure-iot-explorer#541]
**Describe the bug**
When clicking on start telemetry I get an error message stating "Failed to start monitoring device telemetry: [object Object]".  This error goes away if downgrading the version to 0.14.12.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'devices'
2. Click on one of the device IDs
3. Click on Telemetry
4. Clock on the "Start" button
6. See error

**Expected behaviour**
The app should display the telemetry of the selected device.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - App version: 0.14.13.0

**Comment by YingXue** [comment]
Hi @RedDogUK 
We'd like to know if this error is consistent across different hubs.
In 14.13, we rolled out a fix towards exact the issue you see, and it happens when IoT hub is having intermintent connection issue and cann't connect to it's underlying Event hub. 
Unfortunately we are not able to repro this issue in any version (without the help of a broken hub), so it will be great if you can help provide this information to help us triage the issue.

**Comment by helloE9** [comment]
![20220901163156](https://user-images.githubusercontent.com/32892299/187857805-8806aaf1-5adf-4f6c-b044-56325e60af4c.png)
I can send msg to device but can do telemetry to inquire an input.

**Comment by christiannagel** [comment]
I'm seeing the same issue with version 0.14.13. The error is consistent with monitoring.

**Comment by YingXue** [comment]
We apologize for the unreadable error message. We haven't been able to fix it. With the connection string update we did in version 0.14.13, we thought that the error is mitigated. 
We are still suspecting that the connection between iot hub and the underlying event hub is causing this issue. If you an follow my instructions below and verify something for us that will be greatly appreciate.
Please turn on 'Use built-in event hub' toggle and fill in the two values of the event hub, and then start the telemetry monitoring and check  if you are still seeing the error.
![image](https://user-images.githubusercontent.com/5489222/188232288-768c2a85-069c-4c33-a6ff-6e62e9653384.png)
The two values 'connection string' and 'event hub name' can be found on Azure portal:
![image](https://user-images.githubusercontent.com/5489222/188232355-515340a4-d1b9-4bb7-8a0a-c2b980e5f824.png)
In the meanwhile, we will roll back a temporary fix to mitigate the issue you see, but if you can help with this verification, it will be great help!

**Comment by helloE9** [comment]
![20220905101539](https://user-images.githubusercontent.com/32892299/188342223-6274e5b4-dd0b-421e-825a-e6a431ebd6df.png)

with Custom event hub name, I can receive the event.

**Comment by YingXue** [comment]
Fix rolled out: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.14
Closing
