### ISSUE TITLE
[BUG] Cannot sign into Azure using a MSA

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#548]
![image](https://user-images.githubusercontent.com/14916339/189925124-7f6d8829-76f4-415b-a72e-4ad227885350.png)

**Comment by YingXue** [comment]
Thanks for reporting the issue @rido-min, we are looking into this issue. We've got a mixed results of whether signin works for a personal account which is strange as we are making Explorer first party app.
Will update when we got some progress.
Just want to make sure if the shcool/work account is working for you?

**Comment by YingXue** [comment]
Looking into the issue, we want to share several findings:
1. MSA cannot access ARM resource, which is what Explorer needed to query subscriptions and hubs: https://stackoverflow.microsoft.com/questions/134002
2. You should be able to access AAD with a personal account with a tenant, or register an Azure account: https://docs.microsoft.com/en-us/answers/questions/947467/cannot-access-34azure-active-directory34-from-the.html
3. Before user can access Azure portal, there is a step of Azure registration. And thus users can access portal with their MSA account.

Thus, we won't be able to fix this issue.
We would kindly ask our users with personal account to create a tenant, and login with [user1@yourTenantName.onmicrosoft.com](mailto:user1@yourTenantName.onmicrosoft.com) instead, or register an Azure account.
