### ISSUE TITLE
[BUG] DirectMethods/PnP Commands produce Internal server error

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#549]
Since 0.15.0  all commands fail with

```text
Failed to invoke the IoT Plug and Play command 'getRuntimeStats' 
on device 'hub-device-65c5f7498f-bfk6f': 

Error: 
```
```json
{
  "errorCode":500001,
  "trackingId":"09aedd7fbf2c4b7f8ae4183c5f2d6d03-G:0-TimeStamp:09/15/2022 13:35:06",
  "message":"InternalServerError",
  "timestampUtc":"2022-09-15T13:35:06.9897024Z"
}
```

I verified I can invoke the same command on the same device from the portal, so seems an issue with IoTExplorer.

**Comment by Elsie4ever** [comment]
Hi @rido-min, I'm currently on 0.15.0 and tried to run commands in DirectMethods/PnP, both seems work to me and don't have the issue you mentioned repro
![image](https://user-images.githubusercontent.com/22055990/200648081-23a00b15-b401-47b7-939a-4b00b45d4b11.png)
Please let us know if you still have the issue, then we will reopen and investigate, thanks
