### ISSUE TITLE
[BUG] Json View does not use the available space in the current Window

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-explorer#550]
The DeviceTwin viewer, or the DTDL viewer, do not auto-resize to the available screen size, seems like an incorrect padding.

![image](https://user-images.githubusercontent.com/14916339/190420723-cbe71397-bfed-402f-9ea2-3143aca921dd.png)

**Comment by YingXue** [comment]
We made a new release which addressed the issue: 
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.2
