### ISSUE TITLE
[BUG] Wrong Connection string could add connection successfully and read the device list.

### ISSUE THREAD

**Issue by zh0903** [Azure/azure-iot-explorer#553]
**Describe the bug**
Wrong Connection string could add connection successfully and read the device list.

**To Reproduce**
1. Get IoT hub connection string, click add connection, fill it into "connection string" text box.
2. Delete the last character of connection string or add a ' " ' character at its end.
3. Click save.
4. You can view the device list by wrong connection string.

**Expected behavior**
Error arises when saving. 

If the problem is related to cache of previous connection?

**Desktop (please complete the following information):
 - OS: windows
 - OS Version: windows 10
 - App version: 0.15.0

**Comment by YingXue** [comment]
This is not a UI issue.
The last letter in the connection string does not seems to matter when we make the call to service. As long as the service confirms that the SAS token we generated through connection string is valid, the API will return results for the UI to show. 
If you delete, say the last two latters, the api will return 'unauthorized' where the UI will display the error accordingly.
