### ISSUE TITLE
[BUG] The Chocolatey link is broken

### ISSUE THREAD

**Issue by w-azure** [Azure/azure-iot-explorer#561]
I get a 404 when I click on the link that's supposed to take me to the place to install Chocolatey.

Maybe replace with this one: https://chocolatey.org/install

**Comment by YingXue** [comment]
We made a new release with the link removed. Our team decided to end Choco support. Please open feature requests if needed. 
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.2
