### ISSUE TITLE
Telemetry Interval less than 1 second

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/azure-iot-explorer#562]
We track movement from mxchip iot device and telem interval<1s in ms would be instrumental to capture tracking.

**Describe the solution you'd like**
Telemetry Interval less than 1 second in ms

**Describe alternatives you've considered**
hard code mxchip firmware but need to rebuild each time to alter and we have device twin and DT mistmach

**Comment by YingXue** [comment]
This is not a common request, and we suggest following the instructions below and build your own app:
1. Run the app locally or event build it yourself
https://github.com/Azure/azure-iot-explorer#run-it-locally-and-build-it-yourself
2. Change line 39's LOADING_LOCK from 8000 to below 1000 (1000 ms which is 1 second) to suit your use case
3. https://github.com/Azure/azure-iot-explorer/blob/main/src/app/devices/deviceEvents/components/deviceEvents.tsx#L39

**Comment by YingXue** [comment]
We made a new release with updated Event Hub SDK: 
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.2

**Comment by sergiosolorzano** [comment]
Hi @YingXue thanks a bunch for the great work in getting a new release out ! 

This 0.15.2 release seems to address this post for which our team is really grateful. However when trying it how can I enter telemetry interval <1 second? I tried 0.1 but "." is not permitted so I can only enter 01 or 1 second.

<img width="844" alt="question" src="https://user-images.githubusercontent.com/24430655/203657682-b200be17-a8d2-4844-859a-fd34c3012cd0.png">

**Comment by YingXue** [comment]
Hi @sergiosolorzano 
It looks like you've modeled the schema of this command body to be an integer, which is why 0.1 is not allowed. If you change integer to double or float (please refer to the dtdl document for more details), the tool should allow decimals to be entered.

**Comment by sergiosolorzano** [comment]
Hi @YingXue thank you for your guidance. I have validated (DTDL tool) and updated the model (for both device and digital twin just in case they're connected) to telemetryInterval double type, restarted the explorer but issue persists and can't use ".":
<img width="831" alt="explorer" src="https://user-images.githubusercontent.com/24430655/203752168-8ff0685b-5b3f-4721-adb9-668c0df18ad3.png">

<img width="838" alt="explorer2" src="https://user-images.githubusercontent.com/24430655/203752489-a2be4883-9b6f-40d1-85c9-728d1f281d43.png">

I then tested this with float type , restarted explorer but the problem persists:
<img width="842" alt="explorer3" src="https://user-images.githubusercontent.com/24430655/203753643-c0a35a0d-b390-48fc-aa35-00b60109bb2e.png">

<img width="846" alt="explorer4" src="https://user-images.githubusercontent.com/24430655/203753785-c18244eb-0681-4a6d-bfca-6974433dcf0b.png">

**Comment by YingXue** [comment]
Hi @sergiosolorzano do you mind open a new issue separately for the pnp modeling part? It will help prevent the issue being lost in track.

**Comment by YingXue** [comment]
@sergiosolorzano Also, I wanted to let you know that there is workaround for this decimal issue. You can enter 01 in the textbox, and then add the decimal. 
Zero value is giving us a lot of headache in many dtdl related forms. We will need some time to get to the bottom of it judging there is no active development around plug and play for a while.

**Comment by sergiosolorzano** [comment]
Thank you for your notes @YingXue , I appreciate the challenges involved. 

I just [raised the issue](https://github.com/Azure/azure-iot-explorer/issues/586) as requested. From your last note may I please clarify this means we can set interval such as 01.2 means 1.2 seconds? Thank you for your help.

**Comment by YingXue** [comment]
@sergiosolorzano the only tricky case if for any value less than one. 
If you need to input 0.2, please enter 02 and add the dot in between.
Any value greater than 1 should work as is. 1.2 can be entered fine.
