### ISSUE TITLE
[BUG] Failed upgrade azure-iot-explorer from 0.14 version to 0.15 version 

### ISSUE THREAD

**Issue by SerenaAzsphere1** [Azure/azure-iot-explorer#566]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/Azure/azure-iot-explorer/blob/main/README.md'
2. install the explorer tool by Chocolatey, run choco install azure-iot-explorer --pre.
3. azure-iot-exporer 0.14 version was installed after step#2
4. Go to https://github.com/Azure/azure-iot-explorer/releases 
5. download the latest explorer version: [Azure.IoT.Explorer.Preview.0.15.0.msi](https://github.com/Azure/azure-iot-explorer/releases/download/v0.15.0/Azure.IoT.Explorer.Preview.0.15.0.msi)
6. double click on the msi file and install

**Actual result** For step#6, error popped up: Error writing to file: C:\Users\v-serenali\AppData\Local\Programs\Azure-iot-explorer\libEGL.dll, verify that you have access to that directory. 

**Expected behavior**
No error, the azure-iot-explorer should upgrade from 0.14 to 0.15 version 

**Screenshots**
![image](https://user-images.githubusercontent.com/112736530/200039115-62073102-f5a4-40fd-8224-58b239108c45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by YingXue** [comment]
Hi, can you try delete the old version and then install the new one? Also please make sure the old version is not currently opened.
