### ISSUE TITLE
[BUG] The chocolatey installation link doesn't work with 404 page not found error 

### ISSUE THREAD

**Issue by SerenaAzsphere1** [Azure/azure-iot-explorer#567]
**Describe the bug**
the chocolatey installation link doesn't work: https://github.com/Azure/azure-iot-explorer/blob/main/chocolatey.org

**To Reproduce**
1. Go to '[(https://github.com/Azure/azure-iot-explorer/blob/main/README.md)](https://github.com/Azure/azure-iot-explorer/blob/main/README.md)'
2. Click on link 'https://github.com/Azure/azure-iot-explorer/blob/main/chocolatey.org' to install chocolatey
3. See error 404 page not found

**Expected behavior**
The chocolatey link should work and I can install chocolatey 

**Screenshots**
![image](https://user-images.githubusercontent.com/112736530/200043363-4a54c409-110a-40ec-9e97-11d937ea066b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by YingXue** [comment]
Dup of #561
