### ISSUE TITLE
[BUG] Failed install package: miss matched file name package.json and package-lock.json in the repo 

### ISSUE THREAD

**Issue by SerenaAzsphere1** [Azure/azure-iot-explorer#568]
**Describe the bug**

**To Reproduce**
1. Following the instructions: [azure-iot-explorer/README.md at main · Azure/azure-iot-explorer · GitHub](https://github.com/Azure/azure-iot-explorer/blob/main/README.md)
2. Navigate to "Run it locally and build it yourself" -> Open a Node capable command prompt
3. Clone the repo: git clone https://github.com/Azure/azure-iot-explorer.git
4. Run: npm install

**Expected behavior**
install package successfully, no error. 

**Actual result**
C:\Users\Serena>npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Serena/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Serena\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Serena\AppData\Local\npm-cache\_logs\2022-11-04T18_03_24_366Z-debug-0.log

**Screenshots**
![image](https://user-images.githubusercontent.com/112736530/200049055-d44514c6-99a3-48a5-845a-e9951e35b448.png)

Checked the local folder 'C:\Users\Serena\, I found package-lock.json instead of package. json, ​manually change the package-lock.json to package. json, and run the npm install, no error, is this the expect behavior?

![image](https://user-images.githubusercontent.com/112736530/200049587-fd2d104f-8f36-40ad-b4ff-52b7ada2cd9c.png)

![image](https://user-images.githubusercontent.com/112736530/200050737-28d4b1f3-2d6a-4bbb-8075-fb8672276a0d.png)

**Desktop (please complete the following information):**
 - OS:  Windows10, 11

**Comment by YingXue** [comment]
I don't think you are in the this project repo.  After git clone, please cd into the folder and do npm install there.
