### ISSUE TITLE
Unable to get Telemetry for device

### ISSUE THREAD

**Issue by jamesyun7** [Azure/azure-iot-explorer#573]
**Describe the bug**
I have same issue on new release v0.15.1.0 as previous version to monitor device telemetry message.

**To Reproduce**
1. Go to 'Telemetry' of IoT Edge device in Azure IoT Explorer v0.15.1.0
2. Click on 'Start'
3. See error of "Failed to start monitoring device telemetry: Error: "Attempted to perform an unauthorized operation."

**Expected behavior**
Device Explorer can successfully monitor my device telemetry.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/53162885/200720294-c67d8f21-aabc-46b6-9776-6b23ddb65f43.png">

**Screenshots**
<img width="604" alt="image" src="https://user-images.githubusercontent.com/53162885/200719694-aa734dd4-acdd-47c9-848b-58c03cf60f08.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - OS Version: 22H2
 - App version 0.15.1.0
<img width="193" alt="image" src="https://user-images.githubusercontent.com/53162885/200720602-8b774f0e-c375-4d0f-bf9d-f2e8e88e6981.png">

**Comment by YingXue** [comment]
Hi @jamesyun
Please make sure you are using the iot hub connection string with enough permission to monitor device telemetry.

**Comment by zhen9910** [comment]
I got the same issue today. My iothub works fine with IoT Explorer two weeks before, but I find I cannot get device telemetry of this iothub using IoT Explorer now. 

I first used Iot Explorer 0.14.13, then tried 0.15.1, but both didn't work.

**Comment by YingXue** [comment]
Syned with @zhen9910 offline, and we found that a newly created iot hub works fine.
With some investigation, the error resulted from event hub sdk: MessagingError [UnauthorizedError]: InvalidSignature: The token has an invalid signature.
However, we don't have a consistent repro as newly created hub does not have this issue, and thus we cannot provide enough proof if we try to file a bug against event hub team.

I will leave this bug open, and please update us if you run into this issue again, and we can take it from there.

**Comment by lucas-suntao** [comment]
I have met the same problem.Yesterday，it worked well ,but today it shows"Failed to start monitoring device telemetry: Error: "Attempted to perform an unauthorized operation."."Do you have method to solve the problem?

**Comment by YingXue** [comment]
Hi, we are in the middle of updating the event hub sdk. Whiling testing @zhen9910's connection string, we found that the newer version of the sdk did not throw the same error. The event hub team made a fundemental change after a certain version, and we are incorporating the changes. 
The change relatively big, please give us a few more days and we will update the issue once the release is out.
Thanks.

**Comment by russom** [comment]
Hi all - I also ran in the same issue a few days ago. Looking forward to an update

**Comment by russom** [comment]
Good day all - hoping to provide useful info on this, I can say that I still run into the issue when connecting to an IoT Hub in my reference location location (France Central). However, I do **_not_** have the issue when connecting to an IoT Hub in East US, so there seem to be a dependency on the location.
Hopefully we will have a common closure of the issue soon.
Thanks

**Comment by YingXue** [comment]
We made a new release with updated Event Hub SDK: 
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.2
We only got direct access to one of the customer's connection string and verified that the new version fixed issue. As we don't have much data, we will leave the issue open for a while for folks to report update.

**Comment by jamesyun7** [comment]
New release solves this issue. Thanks a lot @YungXue :)

<img width="520" alt="image" src="https://user-images.githubusercontent.com/53162885/203188287-da4aa577-ddbd-4a2c-af6d-4c7bf765b541.png">

**Comment by aleciav** [comment]
Issue solved for me as well. South Europe area

**Comment by russom** [comment]
Confirmed - issue solved. Thanks a lot!

![image](https://user-images.githubusercontent.com/11564340/203273445-49af1e4a-bc83-4b0e-933a-a02eee312aa1.png)

**Comment by wvangeem** [comment]
Issue solved for me (West-Europe).
Thanks!

**Comment by YingXue** [comment]
Thank you folks for the update! We will close the issue.
