### ISSUE TITLE
Editing json Error

### ISSUE THREAD

**Issue by tarodd** [Azure/azure-iot-explorer#574]
**Describe the bug**
You are managing some edge devices that are sending data to Thingworx. We are managing them with Azure IoT Explorer, however, when trying to update the modules using the module twin function we get an error message when saving.

error Failed to update module identity twin for module $edgeAgent: Error: ErrorCode:SystemModuleModifyUnauthorizedAccess;Unauthorized to modify reserved module.;

**To Reproduce**

1. open Azure IoT Explorer 
2. select iOT hub > 
3. select device Devices > 
4. module identities > 
5. $edgeAgent >  
6. Module twin. 
7. When we get to here we attempt to change part of the JSON file and save. This triggers the error message “Failed to update module identity twin for module $edgeAgent:
8.  Error: ErrorCode:SystemModuleModifyUnauthorizedAccess;Unauthorized to modify reserved module

**Expected behavior**
we are expecting the the json to change and updates to save

**Screenshots**

**Comment by YingXue** [comment]
Hi @tarodd 
As this error message is indicating, $edgeAgent is a reserved module which is not allowed to be modified. If you use API directly, I believe it will respond with the same error message. 
We don't have a sophisticated form for users of Explorer to update edge twin like Azure Portal does. I would recommend trying out Azure Portal for your use case.
