### ISSUE TITLE
[BUG] Can't set Telemetry Interval less than 1 second in v0.15.2

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/azure-iot-explorer#586]
[Release 0.15.2 seems to add a feature for lower than 1 second intervals](https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.2). However the UI does not accept decimal places after a zero so can't achieve intervals<1s, "." is not permitted so I can only enter 01 or 1 second.

I have validated the model with (DTDL tool) and updated the model (for both device and digital twin just in case they're connected)  to telemetryInterval double type (also tried float), restarted the explorer but can't use ".":

<img width="749" alt="image" src="https://user-images.githubusercontent.com/24430655/204717315-e9657fa5-e578-4a92-8f24-25ec6ff59bec.png">

<img width="830" alt="image" src="https://user-images.githubusercontent.com/24430655/204717639-b237d1a2-dcfd-4036-b92c-34cf1b39b2c6.png">

<img width="769" alt="image" src="https://user-images.githubusercontent.com/24430655/204717784-84415a53-078f-46be-8213-b0ba9ff17631.png">

<img width="777" alt="image" src="https://user-images.githubusercontent.com/24430655/204717829-24064159-2737-47b1-b5ea-aff0c9b83b77.png">

**To Reproduce**
Add model with interval float or double
Enter telemetryinterval in the UI 0.1

**Expected behavior**
Can enter telemetryinterval 0.1

**Desktop (please complete the following information):**
Iot Explorer 0.15.2
Windows 11 v10.0.22621 Build 22621

**Additional context**
We capture movement with IoT device which requires lower intervals

**Comment by YingXue** [comment]
Fixed released in https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.8. Closing.
