### ISSUE TITLE
How to recognize a local folder as valid DTMI model repository.

### ISSUE THREAD

**Issue by oedze** [Azure/azure-iot-explorer#594]
I am trying to import model definitions using the IoT Explorer. But the IoT Explorer always tells me it can't find any definitions for the model interface i am using. I tried a few things but can't seem to get it to recognize any models.

- I tried selecting the Local folder option in the Iot Plug and Play settings by setting the folder to the exact folder where the json file is located, this didn't help. 
- I tried setting it to iot-plugandplay models folder(which is a direct clone from the github repo) and the device model id to `dtmi:com:example:Thermostat;1`, but with no luck. I did try this with the public repository set, which works, so my device is working properly (i think) 

Some extra information:
- The models were validated with the dmr-client.
- I created the indexes and the expand files for the full repository using [these steps](https://learn.microsoft.com/en-us/azure/iot-develop/concepts-model-repository#create-the-repository-index)

**Comment by rido-min** [comment]
I would expect that local model resolution supports the DMR conventions
/cc @digimaun

**Comment by YingXue** [comment]
Hi @oedze 
It sounds like you are indeed doing things.
We will need you to set up the local file path (for example the path would be d:/ if my Thermostat.json file is in my d drive), and the Thermostat.json.json should have an @id property equals to dtmi:com:example:Thermostat;1 (
![image](https://user-images.githubusercontent.com/5489222/215234882-36eea02f-613b-4c24-b88e-0d6ffaaa653a.png)
)
Once you save the values, the tool should be able to recognize the models.

**Comment by YingXue** [comment]
Closing with instructions given.

**Comment by rido-min** [comment]
I think there is some value by finding files in a folder hierarchy that follows the DMR convention. Do you want to track as a different feature?

**Comment by YingXue** [comment]
Sorry for not reading the descriptions close enough. Yes so far Explorer does not support indexes and the expand file format. I am reopening the issue to investigate what we can do here.

**Comment by oedze** [comment]
> Sorry for not reading the descriptions close enough. Yes so far Explorer does not support indexes and the expand file format. I am reopening the issue to investigate what we can do here.
Hi @YingXue 
yes, as @rido-min  mentioned. I expected the local folder to work as a model repository. When i add the folder it's in the list with a big header above it called: "Model Repository Locations". I now added the thermostat-1.json file to the root of the folder structure and it works indeed. 

It would be nice if the local folder would follow the conventions. 
Maybe it's possible to add an extra option next to add `Public Repository`, `Configurable Repository` and `Local folder` called `Local Repository` . Then you also won't be breaking any local folders that are setup. 

For now i can work with the local folder just fine, Thanks!

**Comment by YingXue** [comment]
We have just release version 0.15.7 and addressed the feature request. Please give it a try if you'd like. Thank you.
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.7
