### ISSUE TITLE
[BUG] Unexpected end of JSON   - CD Message

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-iot-explorer#598]
**Describe the bug**
When sending CD message get  **"Unexpected end of JSON input"**

**To Reproduce**
1. Go to 'The Explorer
2. Configure for IoT Hub.
3. Select the Device
4. Click on "Cloud-to-device-message"'
5. See error

**Expected behavior**
Get an OK message.  
FYI an OK Method message:
```
Successfully invoked method 'stop' on device 'Pico2Dev2' with response {"status":200,"payload":{"request_id":2,"mothod":"stop","parameter":"\"\""}}
```
but with CD Message got:
```
Failed to send message to device Pico2Dev2: Error: invalid json response body at https://pico2hub.azure-devices.net/devices%2FPico2Dev2%2Fmessages%2FdeviceBound?api-version=2020-06-30-preview reason: Unexpected end of JSON input
```

NB: Message is received OK on the device, Also no such error displayed when sendt form VS Code.

**Screenshots**

![Bug](https://user-images.githubusercontent.com/12537105/211183779-dc095b4a-00c9-4d70-a0eb-c20ef5685389.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 11
 - App version - Azure.IoT.Explorer.Preview.0.15.4
**Additional context**

**Comment by djaus2** [comment]
Created a c# Console app as per [https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d#get-the-iot-hub-connection-string](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d#get-the-iot-hub-connection-string). It works OK with no errors.  Have added some ack code to device upon reception of a CD Message and when  Console app is set to DeliveryAcknowledgement.Full  or PostiveOnly console app comes back with Success!

**Comment by GKMesh** [comment]
I am also having this issue

**Comment by EgonRasmussen** [comment]
I have the exact same problem! It works in VSCode, but not in Azure IoT Explorer. Please fix it. It's a wonderful tool - except the bug.

**Comment by YingXue** [comment]
Sorry for the delay of the release. The fix is now out: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.5

**Comment by djaus2** [comment]
Thanks,
Yes all OK now.
I was looking at building it myself an hour ago but this saves me.
Yes is does work ,

David Jones
Microsoft WinHEC/IoT/Embedded/App Development MVP
Sportronics
Australia
***@***.******@***.***>
https://davidjones.sportronics.com.au
GitHub: djaus2<https://github.com/djaus2>
https://mvp.microsoft.com/en-us/PublicProfile/5000301?fullName=David%20%20Jones
http://embedded101.com/Blogs/David-Jones
@IoTMaestro<https://twitter.com/IOTMaestro>

**Comment by djaus2** [comment]
Updated package was posted just now and it does work!
