### ISSUE TITLE
"Direct method" returns "Internal server error"

### ISSUE THREAD

**Issue by shijiong** [Azure/azure-iot-explorer#605]
Azure IoT Explorer Version:  0.15.4

I find that I get the "Internal server error" when I try to call a direct method on remote device. The detail message is as follows:
Failed to invoke method on device RPi4: Error: {"errorCode":500001,"trackingId":"e9e53197cadf4741be7f38de26ba5db8-G:0-TimeStamp:01/29/2023 07:29:30","message":"InternalServerError","timestampUtc":"2023-01-29T07:29:30.9100083Z"}

However, I can make it success with Azure CLI.

**Comment by YingXue** [comment]
Hi @shijiong, the fix was out in version 0.15.5. please give that a try. Close as fixed and dup of #598

**Comment by shijiong** [comment]
Hello, @YingXue , I've tried the version 0.15.5 and this issue is fixed. Thank you!
