### ISSUE TITLE
[BUG] Json data in telemetry should be between single quote

### ISSUE THREAD

**Issue by survivant** [Azure/azure-iot-explorer#606]
**Describe the bug**
The generated command line to send telemetry message in json format is wrap between double quote, which doesn't work.
``az iot device simulate --device-id a-b-c-d-e --login "HostName=XXXX.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=XXXX" --data "{ "test": "1"}"``

**To Reproduce**
just go into the device/send message and enter a json content and click on the copy button and paste it in a terminal

**Expected behavior**

the command line generated should work as is. 

the ouptut should has been
``az iot device simulate --device-id a-b-c-d-e --login "HostName=XXXX.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=XXXX" --data '{ "test": "1"}'`` 

**Screenshots**
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/191879/215490255-67c605cb-13e4-4517-a7b9-a113a1fb8712.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version : 0.15.5.0

**Additional context**

**Comment by YingXue** [comment]
Thank you for reporting the issue. The new release has this bug fixed, please give it a try: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.6
