### ISSUE TITLE
Unable to Focus Away When Starting Telemetry

### ISSUE THREAD

**Issue by gblunden** [Azure/azure-iot-explorer#608]
**Describe the bug**
When running telemetry for a device and trying to switch to another device, an error appears repeatedly and locks the program.

![image](https://user-images.githubusercontent.com/25821616/216077919-2751b870-d965-4c90-a173-dd98953f29e7.png)

To Reproduce

1. Open Device
2. Start Telemetry
3. Move to another device in the breadcrumb

Expected behavior
Can switch between running devices.

Desktop (please complete the following information):
Iot Explorer 0.15.5.0
Windows 11 Version v10.0.22000 Build 22000

**Comment by YingXue** [comment]
Thank you for reporting the issue. The new release has this bug fixed, please give it a try: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.15.6
