### ISSUE TITLE
Telemetry show more than one device in Telemetry stream after device disconnects

### ISSUE THREAD

**Issue by codeputer** [Azure/azure-iot-explorer#621]
**Describe the bug**
Viewing Telemetry from "A" device works and I see my events for the device that I have selected.  Somewhere down the line, however, I start receiving events from "other" devices.  So I'm monitoring GFS010, and over time, I start seeing events from GFS030.  This only happens however if GFS010 loses connectivity (network loss, reboot, etc).

**To Reproduce**
1) From HOME, create a subscription string to the IOT Hub (more than one device should be connected)
2) Then "View devices in this Hub" (which in dark mode is tough to see  - IMO should be a button, or use a tab of the IOT Hubname, and call it Devices, using the real estate to the right.
3) select a "connected" device
4) select "Telemetry"
5) select start
6) Watch the telemetry come in and check the Device Id 
7) reboot the device (fastest) / lose network
8) continue to monitor telemetry and other devices will start displaying

**Expected behavior**
Should only show the telemetry for the device Id selected.  Would be nice to see the status of the device in the Telemetry page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - OS 10
 - App version 0.16.5

**Additional context**
Why can't we instansiate this application twice - throws a JavaScript error.

**Comment by codeputer** [comment]
Any body home? I'm thinking we should have seen a new release by this time?

**Comment by YingXue** [comment]
Hi @codeputer, like you've pointed out in another issue, event hub does not filtering on device, so we are using consumer group to fetch devices, this is a sneak peak of how we use their sdk:
```
new EventHubConsumerClient(params.consumerGroup, await convertIotHubToEventHubsConnectionString(params.hubConnectionString));
```
the granularity stops at the consumer group unfortunately.
i would recommend using different consumer group for different devices.
