### ISSUE TITLE
Invalid workspace error

### ISSUE THREAD

**Issue by jortorri** [Azure/azure-iot-explorer#649]
Hello.
I've one Azure IoT Hub receiving messages and a CosmoDB where the messages are stored. 
I'm using Azure Iot Explorer version 0.15.8.0. in windows 
It connects with my IoT Hub and find devices. But when I click Telemetry option to start receiving messages the application gets stuck on "Receiving events".
Checking with DevTools, there is an error in the "track" call: "Invalid workspace"

![IoTExplorerIssue](https://github.com/Azure/azure-iot-explorer/assets/56599515/ec35193c-e73b-4223-8f2c-c9d394c8c56b)

Any idea?

Thanks in advance.

**Comment by YingXue** [comment]
Hi there,
This track error has nothing to do with real functionalities of the app. It is our internal telemetry system where we use to log user actions, and it's currently broken. Please kindly ignore this error.
