### ISSUE TITLE
[Feature] Support IoT Edge devices

### ISSUE THREAD

**Issue by sebader** [Azure/azure-iot-explorer#90]
[Feature request]
IoT Explorer should support IoT Edge devices. Can be done in multiple steps:

1.  Show column in device list: "Edge: yes/no". Allow to filter on this column
2.  Support showing modules (and module twins) from Edge devices

**Comment by YingXue** [comment]
Hi @sebader , 
Thank you for opening the first issue in the repo!
The edge support is in our longer-term plan, as the current release majorly focus on Plug and Play scenarios (https://docs.microsoft.com/en-us/azure/iot-pnp/overview-iot-plug-and-play).
We will take your request into our future next milestone planning.

Best regards.

**Comment by YingXue** [comment]
Hi @sebader, 
Step 1 has been implemented in this new release [https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.11](url) if you'd like to check it out, while step 2 is still further down the list.
We will close this issue for now, as eventually the tool should reach feature parity as the Azure IoT extension in Azure Portal.
Thanks for your input.
