### ISSUE TITLE
[BUG] Failed to retrieve device list

### ISSUE THREAD

**Issue by SquintEastwood** [Azure/azure-iot-explorer#97]
**Describe the bug**
After copying iothubowner (or any other policy's) connection string primary key from Azure and pasting into the IoT hub connection string box, receive this error as a popup:
"Failed to retrieve device list: 
SyntaxError: Unexpected token N
in JSON at position 4" 

**To Reproduce**
1. Go to Iot Hub in Azure Portal
2. Click on an IoT Hub service
3. Scroll down to Shared access policies under settings
4. Click on iothubowner 
5. Copy connection string--primary key
6. Paste key into Azure IoT explorer, either under Settings and app configuration or under App configurations on program startup
7. Click connect

**Expected behavior**
Expected it to connect to Azure and display devices connected to IoT Hub

**Screenshots**
![image](https://user-images.githubusercontent.com/50408735/63599034-bc7f5480-c58e-11e9-8927-f544578299b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Build 15063
 - App version 0.10.1

**Comment by YingXue** [comment]
Hi @SquintEastwood,
I will close the issue as 'no repro' for now. Please feel free to repo it if it is still happening.

Thank you.

**Comment by andrew-buckley** [comment]
@SquintEastwood we made a change so that you can open developer tools to get a better idea of what might have been failing. If this is still happening for you it would be helpful to show us the network trace and console log for this error.
