### ISSUE TITLE
[BUG] Duplicate Telemetry Data

### ISSUE THREAD

**Issue by matsujirushi** [Azure/azure-iot-explorer#99]
**Describe the bug**
Sometimes, I can see duplicate telemetry data.
For Device Explorer, no problem.

**Screenshots**
when device sent batteryVoltage, actionNum, message. each one.
![image](https://user-images.githubusercontent.com/8079404/63928998-9cb6c780-ca8b-11e9-9180-725f78020390.png)

**Comment by YingXue** [comment]
Hi @matsujirushi 
Thank you for reporting the issue. 
Can you help me understand, if the 6 telemetry items showed up at the same time, or it shows three items first and then another three?
Also, we are planning to add more detailed enqueue time (including miliseconds), so it may help users to identify it is real dups or it is simply due to two messages arrived within the same second.

**Comment by matsujirushi** [comment]
Hi @YingXue ,
>  if the 6 telemetry items showed up at the same time, or it shows three items first and then another three?
It show 6 items same time.

**Comment by YingXue** [comment]
> Hi @YingXue ,
> 
> > if the 6 telemetry items showed up at the same time, or it shows three items first and then another three?
> 
> It show 6 items same time.

Hi @matsujirushi 
How often do you see this happen? I was trying to repro but not able to yet.
Also, if you could help verify if it also happens on another page as follows, it would be very helpful for us to identify the problem:
![image](https://user-images.githubusercontent.com/5489222/64051361-ad207e00-cb2f-11e9-80d6-8ba6de262998.png)

**Comment by YingXue** [comment]
Our new release has just been published. Please give this a try and let us know if it can help identify if these entries are real duplicates.
https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.2

**Comment by matsujirushi** [comment]
Hi @YingXue ,
New release not happened dupulicate telemetry.
But I saw lost telemetry message.

![image](https://user-images.githubusercontent.com/8079404/64084026-ba24b380-cd61-11e9-973f-cee008ac716e.png)

![image](https://user-images.githubusercontent.com/8079404/64084046-f8ba6e00-cd61-11e9-929e-bf3a173358d2.png)

**Comment by YingXue** [comment]
Hi @matsujirushi 
Do you mind use the old explorer to double check if it has the same telemtry loss?
From the console, it seems like it is suppose to be the last telemetry, but from the screenshot of exploere, I cannot directly map the telemetry log to the console log.
Sorry to keep asking you using the old tool for verification.

**Comment by YingXue** [comment]
Closing the issue.
Please reopen if it still repros.
